#EXTM3U
#EXTINF:-1 tvg-id="La 1" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/TVE.png" group-title="TVE" tvg-name="La 1",La 1
https://dh6vo1bovy43s.cloudfront.net/La_1_ES.m3u8
#EXTINF:-1 tvg-id="La 2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/LA2.png" group-title="TVE" tvg-name="La 2",La 2
https://di2qeq48iv8ps.cloudfront.net/La_2_ES.m3u8
#EXTINF:-1 tvg-id="TeleDeporte" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/TDEP.png" group-title="TVE" tvg-name="TeleDeporte",TeleDeporte
https://d2a02gfcid1k4a.cloudfront.net/Teledeporte_ES.m3u8
#EXTINF:-1 tvg-id="Movistar Plus+" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Acestream🇪🇸" tvg-name="Movistar Plus+",Movistar Plus+
acestream://8c67cdb5ba81976662c3a67984a9545d9cfb0f70
#EXTINF:-1 tvg-id="Movistar Plus+ #2" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Acestream🇪🇸" tvg-name="Movistar Plus+ #2",Movistar Plus+ #2
acestream://b6ffbbc72a5b6b579faf79ebac229af7a25b933b
#EXTINF:-1 tvg-id="Movistar Plus+ #3" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Acestream🇪🇸" tvg-name="Movistar Plus+ #3",Movistar Plus+ #3
acestream://5d9a26e0a5f3e5f2ae027bd05635ab9a4fd4b51a
#EXTINF:-1 tvg-id="Movistar Plus+ #4" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Acestream🇪🇸" tvg-name="Movistar Plus+ #4",Movistar Plus+ #4
acestream://5e24a1b9187fccb91553f7c7da4b36341386f74a
#EXTINF:-1 tvg-id="Movistar Plus+ #5" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Acestream🇪🇸" tvg-name="Movistar Plus+ #5",Movistar Plus+ #5
acestream://56ac8e227d526e722624675ccdd91b0cc850582f
#EXTINF:-1 tvg-id="Movistar Plus+ #6" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Acestream🇪🇸" tvg-name="Movistar Plus+ #6",Movistar Plus+ #6
acestream://1ab443f5b4beb6d586f19e8b25b9f9646cf2ab78
#EXTINF:-1 tvg-id="Movistar Plus+ 2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MPLUS2.png" group-title="Acestream🇪🇸" tvg-name="Movistar Plus+ 2",Movistar Plus+ 2
acestream://fbc39d8a9e5d7c9ac6a1438d440104620f54e09c
#EXTINF:-1 tvg-id="LaLigaTV BAR" tvg-logo="https://wiki2023.mundoplus.tv/lib/exe/fetch.php?w=144&h=108&tok=cfd3da&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Flaligatvbar.png" group-title="Acestream🇪🇸" tvg-name="LaLigaTV BAR",LaLigaTV BAR
acestream://608b0faf7d3d25f6fe5dba13d5e4b4142949990e
#EXTINF:-1 tvg-id="DAZN LaLiga" tvg-logo="https://telegra.ph/file/083da39b90492923b30d4.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga",DAZN LaLiga
acestream://f8d5e39a49b9da0215bbd3d9efb8fb3d06b76892
#EXTINF:-1 tvg-id="DAZN LaLiga #2" tvg-logo="https://telegra.ph/file/083da39b90492923b30d4.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga #2",DAZN LaLiga #2
acestream://520950d296c952e1864a08e15af9f89f1ab514ec
#EXTINF:-1 tvg-id="DAZN LaLiga #3" tvg-logo="https://telegra.ph/file/083da39b90492923b30d4.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga #3",DAZN LaLiga #3
acestream://e2b8a4aba2f4ea3dd68992fcdb65c9e62d910b05
#EXTINF:-1 tvg-id="DAZN LaLiga #4" tvg-logo="https://telegra.ph/file/083da39b90492923b30d4.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga #4",DAZN LaLiga #4
acestream://4e6d9cf7d177366045d33cd8311d8b1d7f4bed1f
#EXTINF:-1 tvg-id="M+ LaLiga UHD" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d3/LaLigaTV_UHD_por_Movistar_Plus%2B_2023.png/revision/latest/scale-to-width-down/300?cb=20230708175340" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga UHD",M+ LaLiga UHD
acestream://cc9b7f5fe416069a2110da0909b0f915043c468b
#EXTINF:-1 tvg-id="M+ LaLiga" tvg-logo="https://telegra.ph/file/ede750e0a9de6e726a3f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga",M+ LaLiga
acestream://07f2b92762cfff99bba785c2f5260c7934ca6034
#EXTINF:-1 tvg-id="M+ LaLiga #2" tvg-logo="https://telegra.ph/file/ede750e0a9de6e726a3f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga #2",M+ LaLiga #2
acestream://c32a2cf4631bad4bc40a15ee0f245ed30ad4d85c
#EXTINF:-1 tvg-id="M+ LaLiga #3" tvg-logo="https://telegra.ph/file/ede750e0a9de6e726a3f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga #3",M+ LaLiga #3
acestream://c9321006921967d6258df6945f1d598a5c0cbf1e
#EXTINF:-1 tvg-id="M+ LaLiga #4" tvg-logo="https://telegra.ph/file/ede750e0a9de6e726a3f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga #4",M+ LaLiga #4
acestream://4b528d10eaad747ddf52251206177573ee3e9f74
#EXTINF:-1 tvg-id="M+ LaLiga #5" tvg-logo="https://telegra.ph/file/ede750e0a9de6e726a3f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga #5",M+ LaLiga #5
acestream://00c9bc9c5d7d87680a5a6bed349edfa775a89947
#EXTINF:-1 tvg-id="M+ LaLiga #6" tvg-logo="https://telegra.ph/file/ede750e0a9de6e726a3f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga #6",M+ LaLiga #6
acestream://cc9b7f5fe416069a2110da0909b0f915043c468b
#EXTINF:-1 tvg-id="M+ LaLiga #7" tvg-logo="https://telegra.ph/file/ede750e0a9de6e726a3f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga #7",M+ LaLiga #7
acestream://14b6cd8769cd485f2cffdca64be9698d9bfeac58
#EXTINF:-1 tvg-id="LaLiga Hypermotion" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion",LaLiga Hypermotion
acestream://f15f997f457e49ad9697e65cf2d78db26ee875b9
#EXTINF:-1 tvg-id="LaLiga Hypermotion #2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion #2",LaLiga Hypermotion #2
acestream://87bb542f974b6b9e89d0f2e20ed6dc93426f4be0
#EXTINF:-1 tvg-id="LaLiga Hypermotion #3" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion #3",LaLiga Hypermotion #3
acestream://a4f072c9b614323ac1258a175f868a909ea3c8cd
#EXTINF:-1 tvg-id="Eurosport 1" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1",Eurosport 1
acestream://bae98f69fbf867550b4f73b4eb176dae84d7f909
#EXTINF:-1 tvg-id="Eurosport 1 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 #2",Eurosport 1 #2
acestream://714e14e6d6e27660fd25a75b57b0ac5580fe705d
#EXTINF:-1 tvg-id="Eurosport 1 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 #3",Eurosport 1 #3
acestream://704e51760a644bc90aa22269bf84139947a0414a
#EXTINF:-1 tvg-id="Eurosport 1 #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 #4",Eurosport 1 #4
acestream://16ffa1713f42aa27317ee039a2bd0cdbc89a1580
#EXTINF:-1 tvg-id="Eurosport 1 #5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 #5",Eurosport 1 #5
acestream://c3da6c4f91d9d10ade00318a869435e19f204d0e
#EXTINF:-1 tvg-id="Eurosport 1 #6" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 #6",Eurosport 1 #6
acestream://d830c1dc3b74e74f79cbb823804cf2037857e78a
#EXTINF:-1 tvg-id="Eurosport 1 #7" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 #7",Eurosport 1 #7
acestream://cfa75ade53810dac64411b22d56c3d4582a221d3
#EXTINF:-1 tvg-id="Eurosport 1 #8" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 #8",Eurosport 1 #8
acestream://1b0bc4d4dcd609d3c092712e721392b199f50a62
#EXTINF:-1 tvg-id="Eurosport 2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=6fee42&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes2.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 2",Eurosport 2
acestream://dc4ccb9e72550bc72be9360aa7d77e337ad11ecc
#EXTINF:-1 tvg-id="Eurosport 2 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=6fee42&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes2.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 2 #2",Eurosport 2 #2
acestream://2773b39926d15dd3d9495d94c4050604792d7031
#EXTINF:-1 tvg-id="Eurosport 2 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=6fee42&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes2.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 2 #3",Eurosport 2 #3
acestream://0585e09bb8ac9720e4c11934f1b184e309291551
#EXTINF:-1 tvg-id="Eurosport 2 #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=6fee42&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes2.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 2 #4",Eurosport 2 #4
acestream://5c910d614894635153a7d42de98cc2e4a958a53f
#EXTINF:-1 tvg-id="Vamos" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos",Vamos
acestream://3b2a8b41e7097c16b0468b42d7de0320886fa933
#EXTINF:-1 tvg-id="Vamos #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #2",Vamos #2
acestream://2940120bf034db79a7f5849846ccea0255172eae
#EXTINF:-1 tvg-id="Vamos #3" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #3",Vamos #3
acestream://57313e1ef438538df4feb5a6028dc78ee4f66b6a
#EXTINF:-1 tvg-id="Vamos #4" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #4",Vamos #4
acestream://651d6be899d1fafa107a265a9dc00ff914c1b548
#EXTINF:-1 tvg-id="Vamos #5" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #5",Vamos #5
acestream://1444a976d2cf6e7fdcee833ed36ee5e55632253f
#EXTINF:-1 tvg-id="Vamos #6" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #6",Vamos #6
acestream://d03c13b6723f66155d7a0df3692a3b073fe630f2
#EXTINF:-1 tvg-id="Vamos #7" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #7",Vamos #7
acestream://12ba546d229bc39f01c3c18988a034b215fe6adb
#EXTINF:-1 tvg-id="Vamos #8" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #8",Vamos #8
acestream://c7c81acdd1a03ecc418c94c2f28e2adb0556c40b
#EXTINF:-1 tvg-id="Vamos #9" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Vamos_por_Movistar_Plus%2B_2023.svg/revision/latest/scale-to-width-down/250?cb=20230728170813" group-title="Acestream🇪🇸" tvg-name="Vamos #9",Vamos #9
acestream://0e5d8c9724fa9163f49096b70484e315251eb785
#EXTINF:-1 tvg-id="M+ Deportes" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes",M+ Deportes
acestream://ef9dcc4eaac36a0f608b52a31f8ab237859e071a
#EXTINF:-1 tvg-id="M+ Deportes #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #2",M+ Deportes #2
acestream://332d8fdeb9c51385230b8c9448e047ccc4a6355d
#EXTINF:-1 tvg-id="M+ Deportes #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #3",M+ Deportes #3
acestream://9099f519dd9b6b6f74f105477ff545829a110415
#EXTINF:-1 tvg-id="M+ Deportes #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #4",M+ Deportes #4
acestream://be02b9918b8fe7224cfa9af1e37856760f95b1b8
#EXTINF:-1 tvg-id="M+ Deportes #5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #5",M+ Deportes #5
acestream://751b9cb03d188ce70e6aac22c1bfb16a5d0b2237
#EXTINF:-1 tvg-id="M+ Deportes #6" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #6",M+ Deportes #6
acestream://acb510858f34c3c6fd5f79395b031abd6885c2b3
#EXTINF:-1 tvg-id="M+ Deportes #7" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #7",M+ Deportes #7
acestream://ebca4a63ce3bfda7b272964a1acc5227218184a4
#EXTINF:-1 tvg-id="M+ Deportes #8" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #8",M+ Deportes #8
acestream://3a74d9869b13e763476800740c6625e715a39879
#EXTINF:-1 tvg-id="M+ Deportes #9" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=fdf4c9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmde.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes #9",M+ Deportes #9
acestream://2f3cfd199a49819cbd129689a840dc3d23ab93aa
#EXTINF:-1 tvg-id="M+ Deportes 2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=e194d0&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem2.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 2",M+ Deportes 2
acestream://edd06f11e1cef292a1d795e15207ef2f580e298c
#EXTINF:-1 tvg-id="M+ Deportes 2 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=e194d0&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem2.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 2 #2",M+ Deportes 2 #2
acestream://438991226c3bc6a06e7bfda9bea9f769957dc366
#EXTINF:-1 tvg-id="M+ Deportes 2 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=e194d0&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem2.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 2 #3",M+ Deportes 2 #3
acestream://f0ee7a2b43c1df5ea9e4fac5bf876d5bef4372b0
#EXTINF:-1 tvg-id="M+ Deportes 2 #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=e194d0&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem2.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 2 #4",M+ Deportes 2 #4
acestream://639c561dd57fa3fc91fde715caeb696c5efb7ce7
#EXTINF:-1 tvg-id="M+ Deportes 2 #5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=e194d0&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem2.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 2 #5",M+ Deportes 2 #5
acestream://bfa01c11c5c6b7a616a516de4f2c769a89d26b25
#EXTINF:-1 tvg-id="M+ Deportes 3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=ff9e95&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem3.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 3",M+ Deportes 3
acestream://753d4b1f7c4ef43238b5cf23b05572b550a44eee
#EXTINF:-1 tvg-id="M+ Deportes 3 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=ff9e95&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem3.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 3 #2",M+ Deportes 3 #2
acestream://81e100e3fee4def126eb37280327cf43ce48c639
#EXTINF:-1 tvg-id="M+ Deportes 3 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=ff9e95&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem3.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 3 #3",M+ Deportes 3 #3
acestream://799c6b5ee1cf41af077d14e3f9c45a32697eb903
#EXTINF:-1 tvg-id="M+ Deportes 3 #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=ff9e95&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem3.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 3 #4",M+ Deportes 3 #4
acestream://2fd410c5d89e7a627cd3785685b7915b8e4bd534
#EXTINF:-1 tvg-id="M+ Deportes 4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f897b7&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem4.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 4",M+ Deportes 4
acestream://58a4c880ab18486d914751db32a12760e74b75a4
#EXTINF:-1 tvg-id="M+ Deportes 4 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f897b7&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem4.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 4 #2",M+ Deportes 4 #2
acestream://b40e1de2dcbd7c665f54877b14c830ed67b32a96
#EXTINF:-1 tvg-id="M+ Deportes 5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=819fdc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem5.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 5",M+ Deportes 5
acestream://2d19e39c92f7d8ce90b271d8aaf6f42e733eedc2
#EXTINF:-1 tvg-id="M+ Deportes 5 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=819fdc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem5.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 5 #2",M+ Deportes 5 #2
acestream://7b361369a40046ad3011086f9d4ae2982fb4d5aa
#EXTINF:-1 tvg-id="M+ Deportes 5 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=819fdc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem5.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 5 #3",M+ Deportes 5 #3
acestream://fcc0fd75bf1dba40b108fcf0d3514e0e549bfbac
#EXTINF:-1 tvg-id="M+ Deportes 6" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=cdf512&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem6.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 6",M+ Deportes 6
acestream://e4124b2143ed75e5ce902bed61be08cc5e5c3c03
#EXTINF:-1 tvg-id="M+ Deportes 6 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=cdf512&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem6.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 6 #2",M+ Deportes 6 #2
acestream://190a81938c2ddc6fe97758271f8c48f4db31c28a
#EXTINF:-1 tvg-id="M+ Deportes 6 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=cdf512&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem6.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 6 #3",M+ Deportes 6 #3
acestream://cc5782d37ae6b6e0bab396dd64074982d0879046
#EXTINF:-1 tvg-id="M+ Deportes 7" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=847a45&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmdem7.png" group-title="Acestream🇪🇸" tvg-name="M+ Deportes 7",M+ Deportes 7
acestream://070f82d6443a52962d6a2ed9954c979b29404932
#EXTINF:-1 tvg-id="Tennis Channel" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/b4/Tennis_Channel.svg/revision/latest/scale-to-width-down/165?cb=20150207234929" group-title="Acestream🇪🇸" tvg-name="Tennis Channel",Tennis Channel
acestream://039fae21c9e7e5214d3d898cba80863e37e623ac
#EXTINF:-1 tvg-id="Tennis Channel #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/b4/Tennis_Channel.svg/revision/latest/scale-to-width-down/165?cb=20150207234929" group-title="Acestream🇪🇸" tvg-name="Tennis Channel #2",Tennis Channel #2
acestream://8091334c82e8720fc6aa05ff0bd6d343c5bfecbf
#EXTINF:-1 tvg-id="SuperTennis🇮🇹" tvg-logo="https://www.ubitennis.com/wp-content/uploads/2020/09/Supertennis-Logo-Copia.jpg" group-title="Acestream🇪🇸" tvg-name="SuperTennis🇮🇹",SuperTennis🇮🇹
acestream://b58dbf92765976b308695f62dea94b00b40730ee
#EXTINF:-1 tvg-id="Ellas Vamos" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MELLAV.png" group-title="Acestream🇪🇸" tvg-name="Ellas Vamos",Ellas Vamos
acestream://9b84af74b2fa3690c519199326fc2f181b025cdd
#EXTINF:-1 tvg-id="Ellas Vamos #2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MELLAV.png" group-title="Acestream🇪🇸" tvg-name="Ellas Vamos #2",Ellas Vamos #2
acestream://d8c2ed470e847154a88f011137cc206319f6bed5
#EXTINF:-1 tvg-id="DAZN 1" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn1.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 1",DAZN 1
acestream://6538b79ce0da657d8455d1da6a5f342398899a0e
#EXTINF:-1 tvg-id="DAZN 1 #2" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn1.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 1 #2",DAZN 1 #2
acestream://50a8a13c474848d1efbd5586efdb5b6cdd173fa9
#EXTINF:-1 tvg-id="DAZN 1 #3" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn1.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 1 #3",DAZN 1 #3
acestream://4141892f5df7d6474bf0279895ce02b7336c9928
#EXTINF:-1 tvg-id="DAZN 1 #4" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn1.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 1 #4",DAZN 1 #4
acestream://ee4dc45720d3ec283f61189fbfc120c91d5141bf
#EXTINF:-1 tvg-id="DAZN 1 #5" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn1.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 1 #5",DAZN 1 #5
acestream://eb6ffec065b26259ad3d1811e0bbb0a5332ed276
#EXTINF:-1 tvg-id="DAZN 1 #6" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn1.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 1 #6",DAZN 1 #6
acestream://d5b2c6b940cf3df5e8f9dc6f000f0ea23a10b151
#EXTINF:-1 tvg-id="DAZN 1 Bar" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=c3e080&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznbar01.png" group-title="Acestream🇪🇸" tvg-name="DAZN 1 Bar",DAZN 1 Bar
acestream://688e785893b50acc1d00cb37f15bfc42e72f5ae3
#EXTINF:-1 tvg-id="DAZN 2" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn2.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 2",DAZN 2
acestream://8b081c8afbd9beafc8c5fbf0115eb36eadb07a35
#EXTINF:-1 tvg-id="DAZN 2 #2" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn2.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 2 #2",DAZN 2 #2
acestream://fb2dd566824658eeab27aae19a01c09430f1a97d
#EXTINF:-1 tvg-id="DAZN 2 #3" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn2.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 2 #3",DAZN 2 #3
acestream://0f5402f75107112d59d924a5f381cfed33dbe6d2
#EXTINF:-1 tvg-id="DAZN 2 #4" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn2.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 2 #4",DAZN 2 #4
acestream://ca923c9873fd206a41c1e83ff8fc40e3cf323c9a
#EXTINF:-1 tvg-id="DAZN 2 #5" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn2.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 2 #5",DAZN 2 #5
acestream://a929eeec1268d69d1556a2e3ace793b2577d8810
#EXTINF:-1 tvg-id="DAZN 2 #6" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn2.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 2 #6",DAZN 2 #6
acestream://ae68a0835039fab28fd2314108fabd4fab33b8ab
#EXTINF:-1 tvg-id="DAZN 2 #7" tvg-logo="https://i2.wp.com/jungle-team.com/wp-content/uploads/2021/01/dazn2.png?fit=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 2 #7",DAZN 2 #7
acestream://b0eabe0fdd02fdd165896236765a9b753a2ff516
#EXTINF:-1 tvg-id="DAZN 2 Bar" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=b795bf&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznbar02.png" group-title="Acestream🇪🇸" tvg-name="DAZN 2 Bar",DAZN 2 Bar
acestream://2f9211669499f413dab1a490198afab2a9b4b57c
#EXTINF:-1 tvg-id="DAZN 3" tvg-logo="https://i0.wp.com/jungle-team.com/wp-content/uploads/2021/03/dazn3.png?resize=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 3",DAZN 3
acestream://d641cd0fca0f467b3130754a091e2f4d22e68eb1
#EXTINF:-1 tvg-id="DAZN 3 #2" tvg-logo="https://i0.wp.com/jungle-team.com/wp-content/uploads/2021/03/dazn3.png?resize=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 3 #2",DAZN 3 #2
acestream://3785f04aa15a5e6ef1484f0bea7f4664f2c1a4ea
#EXTINF:-1 tvg-id="DAZN 3 #3" tvg-logo="https://i0.wp.com/jungle-team.com/wp-content/uploads/2021/03/dazn3.png?resize=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 3 #3",DAZN 3 #3
acestream://d1d9ec2361a6ac8edc0b2841866383768cc28df9
#EXTINF:-1 tvg-id="DAZN 4" tvg-logo="https://i0.wp.com/jungle-team.com/wp-content/uploads/2021/03/dazn4.png?resize=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 4",DAZN 4
acestream://7e27e46c25d4308d16098d9dc67fcd8736e8c1f0
#EXTINF:-1 tvg-id="DAZN 4 #2" tvg-logo="https://i0.wp.com/jungle-team.com/wp-content/uploads/2021/03/dazn4.png?resize=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 4 #2",DAZN 4 #2
acestream://c015d37d1ead8155b1e7b97e743a1fe9850f0af5
#EXTINF:-1 tvg-id="DAZN 4 #3" tvg-logo="https://i0.wp.com/jungle-team.com/wp-content/uploads/2021/03/dazn4.png?resize=440%2C264&ssl=1" group-title="Acestream🇪🇸" tvg-name="DAZN 4 #3",DAZN 4 #3
acestream://7e90956539f4e1318a63f3960e4f75c7c7c5a3b8
#EXTINF:-1 tvg-id="DAZN F1" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1",DAZN F1
acestream://6422e8bc34282871634c81947be093c04ad1bb29
#EXTINF:-1 tvg-id="DAZN F1 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #2",DAZN F1 #2
acestream://c9c18ae7a9dafba1caae5beb22060f9c92bba553
#EXTINF:-1 tvg-id="DAZN F1 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #3",DAZN F1 #3
acestream://515efd8115482bda8d92aa6df9a882a5e5797494
#EXTINF:-1 tvg-id="DAZN F1 #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #4",DAZN F1 #4
acestream://82b4f249788f93b8f9ce968803662d7cd4f1b8cc
#EXTINF:-1 tvg-id="DAZN F1 #5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #5",DAZN F1 #5
acestream://d5cf2dfa4fb4165ce58bf9db815088c28fec7711
#EXTINF:-1 tvg-id="DAZN F1 #6" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #6",DAZN F1 #6
acestream://8c1155cdfae76eb582290c04904c98da066657c9
#EXTINF:-1 tvg-id="DAZN F1 #7" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #7",DAZN F1 #7
acestream://ba6e1bdc8e03da60ff572557645eb04370af0cd0
#EXTINF:-1 tvg-id="DAZN F1 #8" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #8",DAZN F1 #8
acestream://b08e158ea3f5c72084f5ff8e3c30ca2e4d1ff6d1
#EXTINF:-1 tvg-id="DAZN F1 #9" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #9",DAZN F1 #9
acestream://bcf9dc38f92e90a71b87bd54b3bac91b76d09a69
#EXTINF:-1 tvg-id="DAZN F1 #10" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #10",DAZN F1 #10
acestream://fd53cfa7055fe458d4f5c0ff59a06cd43723be55
#EXTINF:-1 tvg-id="DAZN F1 #11" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=128871&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznf1.png" group-title="Acestream🇪🇸" tvg-name="DAZN F1 #11",DAZN F1 #11
acestream://ed6188dcbb491efeb2092c1a6199226c27f61727
#EXTINF:-1 tvg-id="F1 TV🇪🇸" tvg-logo="https://i0.wp.com/thef1spectator.com/wp-content/uploads/2019/07/F1-TV-pro-300x157.png" group-title="Acestream🇪🇸" tvg-name="F1 TV🇪🇸",F1 TV🇪🇸
acestream://5789ca155323664edd293b848606688edf803f4d
#EXTINF:-1 tvg-id="F1 TV🇬🇧" tvg-logo="https://i0.wp.com/thef1spectator.com/wp-content/uploads/2019/07/F1-TV-pro-300x157.png" group-title="Acestream🇪🇸" tvg-name="F1 TV🇬🇧",F1 TV🇬🇧
acestream://0b7bd581b0eae65396b96a4efe4491a2dd1ba088
#EXTINF:-1 tvg-id="skysportsF1🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/1a/Sky_Sports_F1_2020.svg/revision/latest/scale-to-width-down/300?cb=20200924152412" group-title="Acestream🇪🇸" tvg-name="skysportsF1🇬🇧",skysportsF1🇬🇧
acestream://6605856eb8ff5d4154bedb4b5c58952c0e90db48
#EXTINF:-1 tvg-id="sky sport F1🇩🇪" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Sky_Sport_F1_-_Logo_2020.svg/768px-Sky_Sport_F1_-_Logo_2020.svg.png" group-title="Acestream🇪🇸" tvg-name="sky sport F1🇩🇪",sky sport F1🇩🇪
acestream://b04372b9543d763bd2dbd2a1842d9723fd080076
#EXTINF:-1 tvg-id="DAZN Eventos 1🇬🇧" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/DAZN_logo.svg/768px-DAZN_logo.svg.png" group-title="Acestream🇪🇸" tvg-name="DAZN Eventos 1🇬🇧",DAZN Eventos 1🇬🇧
acestream://176f0b8565a161f87c81a4a250463e3eaf678fb5
#EXTINF:-1 tvg-id="DAZN Eventos 2🇬🇧" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/DAZN_logo.svg/768px-DAZN_logo.svg.png" group-title="Acestream🇪🇸" tvg-name="DAZN Eventos 2🇬🇧",DAZN Eventos 2🇬🇧
acestream://8bdeb6055da0be3bd1e1977dbf3640408f7d0267
#EXTINF:-1 tvg-id="DAZN Eventos 3🇬🇧" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/DAZN_logo.svg/768px-DAZN_logo.svg.png" group-title="Acestream🇪🇸" tvg-name="DAZN Eventos 3🇬🇧",DAZN Eventos 3🇬🇧
acestream://4b048bcfaed7daec454e88f0e29b56756300447d
#EXTINF:-1 tvg-id="F1 TV 55 Carlos Sainz🇪🇸" tvg-logo="https://i0.wp.com/thef1spectator.com/wp-content/uploads/2019/07/F1-TV-pro-300x157.png" group-title="Acestream🇪🇸" tvg-name="F1 TV 55 Carlos Sainz🇪🇸",F1 TV 55 Carlos Sainz🇪🇸
acestream://ddc3b1c8297d57d8096ba20edc1da41eb149a167
#EXTINF:-1 tvg-id="F1 TV 14 Fernando Alonso🇪🇸" tvg-logo="https://i0.wp.com/thef1spectator.com/wp-content/uploads/2019/07/F1-TV-pro-300x157.png" group-title="Acestream🇪🇸" tvg-name="F1 TV 14 Fernando Alonso🇪🇸",F1 TV 14 Fernando Alonso🇪🇸
acestream://a97ccf39516515e7812d5c04dcacdf748f3545e8
#EXTINF:-1 tvg-id="MGPTV Onboard 1" tvg-logo="https://cdn-7.motorsport.com/images/mgl/YN1RZ4b2/s1000/motogp-logo.webp" group-title="Acestream🇪🇸" tvg-name="MGPTV Onboard 1",MGPTV Onboard 1
acestream://2e764a7ad94bcb4e67e82369b7aa982c6b2751b4
#EXTINF:-1 tvg-id="MGPTV Onboard 2" tvg-logo="https://cdn-7.motorsport.com/images/mgl/YN1RZ4b2/s1000/motogp-logo.webp" group-title="Acestream🇪🇸" tvg-name="MGPTV Onboard 2",MGPTV Onboard 2
acestream://b926e6a6ab1d5dc855ce2d3dbeb5e97b9d42b304
#EXTINF:-1 tvg-id="MGPTV Onboard 3" tvg-logo="https://cdn-5.motorsport.com/images/mgl/YN1RZ4b2/s1200/motogp-logo.webp" group-title="Acestream🇪🇸" tvg-name="MGPTV Onboard 3",MGPTV Onboard 3
acestream://9798df57203105309f47b1aa81b6badf00fd0f35
#EXTINF:-1 tvg-id="MGPTV Onboard 4" tvg-logo="https://cdn-5.motorsport.com/images/mgl/YN1RZ4b2/s1200/motogp-logo.webp" group-title="Acestream🇪🇸" tvg-name="MGPTV Onboard 4",MGPTV Onboard 4
acestream://de3ae87e72054cf3ce75268753845c97b931ad58
#EXTINF:-1 tvg-id="M+ Golf" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOLF+.png" group-title="Acestream🇪🇸" tvg-name="M+ Golf",M+ Golf
acestream://8546cff89e4ee8bf3ad31cf6457c3bc2c4341031
#EXTINF:-1 tvg-id="M+ Golf #2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOLF+.png" group-title="Acestream🇪🇸" tvg-name="M+ Golf #2",M+ Golf #2
acestream://9be118a64eb603b5eb62be6cf27631d3891b5174
#EXTINF:-1 tvg-id="M+ Golf #3" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOLF+.png" group-title="Acestream🇪🇸" tvg-name="M+ Golf #3",M+ Golf #3
acestream://76a69812c66bfc4899e89df498220588a56e6064
#EXTINF:-1 tvg-id="M+ Golf #4" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOLF+.png" group-title="Acestream🇪🇸" tvg-name="M+ Golf #4",M+ Golf #4
acestream://872608e734992db636eb79426802cd08f4029afb
#EXTINF:-1 tvg-id="M+ Golf 2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOLF2.png" group-title="Acestream🇪🇸" tvg-name="M+ Golf 2",M+ Golf 2
acestream://96e82321c731e41768a806992ee4d3b9b7a0e7d7
#EXTINF:-1 tvg-id="Liga de Campeones HDR" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/CHHDR.png" group-title="Acestream🇪🇸" tvg-name="Liga de Campeones HDR",Liga de Campeones HDR
acestream://152169ce99e1fd27f2249c18384a121079cdef29
#EXTINF:-1 tvg-id="M+ Liga de Campeones" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones",M+ Liga de Campeones
acestream://778f08cbae9596ed9e8b2ae0af33ee7a6fe24c6a
#EXTINF:-1 tvg-id="M+ Liga de Campeones #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #2",M+ Liga de Campeones #2
acestream://afbf2a479c5a5072698139f0f556ef3e77a99bd0
#EXTINF:-1 tvg-id="M+ Liga de Campeones #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #3",M+ Liga de Campeones #3
acestream://680187938f9305cce3ae240298f10e8695bf77c2
#EXTINF:-1 tvg-id="M+ Liga de Campeones #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #4",M+ Liga de Campeones #4
acestream://5c15c639207a080183b12fa63282b409c07401d6
#EXTINF:-1 tvg-id="M+ Liga de Campeones #5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #5",M+ Liga de Campeones #5
acestream://97df5b7824948972d041d8ca2a4d29c90b641bc9
#EXTINF:-1 tvg-id="M+ Liga de Campeones #6" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #6",M+ Liga de Campeones #6
acestream://2b51710cee513e8939785fa3e7980f32d4e0415f
#EXTINF:-1 tvg-id="M+ Liga de Campeones #7" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #7",M+ Liga de Campeones #7
acestream://9db029dff6a9c637d1f670e78dbc1a479b9b406e
#EXTINF:-1 tvg-id="M+ Liga de Campeones #8" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #8",M+ Liga de Campeones #8
acestream://e572a5178ff72eed7d1d751a18b4b3419699f370
#EXTINF:-1 tvg-id="M+ Liga de Campeones #9" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=73a021&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones #9",M+ Liga de Campeones #9
acestream://b028202ff335911db3118bceac027df3e8ef6c32
#EXTINF:-1 tvg-id="M+ Liga de Campeones 2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=399bb7&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc2.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 2",M+ Liga de Campeones 2
acestream://74ab4e4ec7e2da001f473ca40893b7307b8029c5
#EXTINF:-1 tvg-id="M+ Liga de Campeones 2 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=399bb7&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc2.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 2 #2",M+ Liga de Campeones 2 #2
acestream://abdf9058786a48623d0de51a3adb414ae10b6e72
#EXTINF:-1 tvg-id="M+ Liga de Campeones 2 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=399bb7&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc2.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 2 #3",M+ Liga de Campeones 2 #3
acestream://38f7b2044e549df2039ff26cefa6f9a60c854d5e
#EXTINF:-1 tvg-id="M+ Liga de Campeones 3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=446d14&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc3.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 3",M+ Liga de Campeones 3
acestream://4416843c96b7f7a1bc55c476091a60fff0922bc7
#EXTINF:-1 tvg-id="M+ Liga de Campeones 3 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=446d14&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc3.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 3 #2",M+ Liga de Campeones 3 #2
acestream://cfc371890bfb502737a26de5215e50929c52d0f9
#EXTINF:-1 tvg-id="DAZN Bundesliga 1🇪🇸🇩🇪🇬🇧" tvg-logo="https://sportal365images.com/process/smp-images-production/ringier.africa/21042024/6ce0786b-1026-4516-a0f1-02efb83bdb72.png?operations=fit(960:)" group-title="Acestream🇪🇸" tvg-name="DAZN Bundesliga 1🇪🇸🇩🇪🇬🇧",DAZN Bundesliga 1🇪🇸🇩🇪🇬🇧
acestream://cb18d080d81f7fccf26b7723ce6a5d86d31220db
#EXTINF:-1 tvg-id="DAZN Bundesliga 2🇪🇸🇩🇪🇬🇧" tvg-logo="https://sportal365images.com/process/smp-images-production/ringier.africa/21042024/6ce0786b-1026-4516-a0f1-02efb83bdb72.png?operations=fit(960:)" group-title="Acestream🇪🇸" tvg-name="DAZN Bundesliga 2🇪🇸🇩🇪🇬🇧",DAZN Bundesliga 2🇪🇸🇩🇪🇬🇧
acestream://d4f56cda0a15f47e7820daaac8e37b4d67d9c918
#EXTINF:-1 tvg-id="DAZN Bundesliga 3🇪🇸🇩🇪🇬🇧" tvg-logo="https://sportal365images.com/process/smp-images-production/ringier.africa/21042024/6ce0786b-1026-4516-a0f1-02efb83bdb72.png?operations=fit(960:)" group-title="Acestream🇪🇸" tvg-name="DAZN Bundesliga 3🇪🇸🇩🇪🇬🇧",DAZN Bundesliga 3🇪🇸🇩🇪🇬🇧
acestream://692d6a47ba99fbfc67fa947e468e859c7f2b9564
#EXTINF:-1 tvg-id="Servus TV 🇩🇪" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/c/ca/ServusTV_2015.svg/revision/latest/scale-to-width-down/250?cb=20231112154013" group-title="Acestream🇪🇸" tvg-name="Servus TV 🇩🇪",Servus TV 🇩🇪
acestream://988f4d88d74ec0d2b3584f6c7e067fcbdb501115
#EXTINF:-1 tvg-id="Ziggo Sport 🇳🇱" tvg-logo="https://cdn.broadbandtvnews.com/wp-content/uploads/2015/12/14120446/Ziggo_Sport.jpg" group-title="Acestream🇪🇸" tvg-name="Ziggo Sport 🇳🇱",Ziggo Sport 🇳🇱
acestream://fcd7621df513f600652b4813d5d8fd1daed60058
#EXTINF:-1 tvg-id="Ziggo Sport 2 🇳🇱" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/fc/Ziggo_Sport_2.svg/revision/latest/scale-to-width-down/250?cb=20240702091554" group-title="Acestream🇪🇸" tvg-name="Ziggo Sport 2 🇳🇱",Ziggo Sport 2 🇳🇱
acestream://95769f95c6af45e8ec46526c3be1104d0a0c7b91
#EXTINF:-1 tvg-id="RedBull TV 🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/3/3c/Red_Bull_TV.svg/revision/latest/scale-to-width-down/250?cb=20180423100712" group-title="Acestream🇪🇸" tvg-name="RedBull TV 🇬🇧",RedBull TV 🇬🇧
acestream://fefd91766cef2af2bf4ded328633fb01051d6df9
#EXTINF:-1 tvg-id="Eurosport 1🇷🇺" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1🇷🇺",Eurosport 1🇷🇺
acestream://f5a5a5bf9903bde0c865e421f126c42e514ff787
#EXTINF:-1 tvg-id="Eurosport 1🇷🇺 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1🇷🇺 #2",Eurosport 1🇷🇺 #2
acestream://cfa75ade53810dac64411b22d56c3d4582a221d3
#EXTINF:-1 tvg-id="Eurosport 1🇷🇺 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1🇷🇺 #3",Eurosport 1🇷🇺 #3
acestream://23a4937f1484b435af132dbfb3e8fd3aefc9baad
#EXTINF:-1 tvg-id="Eurosport 1 🇩🇪" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=f2fedc&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 1 🇩🇪",Eurosport 1 🇩🇪
acestream://b8cad4710b1c3b2b84a82c1ece40c08517b8f766
#EXTINF:-1 tvg-id="Eurosport 2 🇩🇪" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=6fee42&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes2.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 2 🇩🇪",Eurosport 2 🇩🇪
acestream://ac675c82d6dfd4a201532c18b42e48dacb7c32c6
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪",Eurosport 360 🇩🇪
acestream://22df9a5fae8cae52fec925c2bb44b74f96a4200c
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #2",Eurosport 360 🇩🇪 #2
acestream://57f95543ac41656d473b1a27123fc413388a728c
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #3" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #3",Eurosport 360 🇩🇪 #3
acestream://7adbca42657ace1fe228142d351d0896974bbe0c
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #4",Eurosport 360 🇩🇪 #4
acestream://1b6b6c0ddc0534236b3bae78f41d2bc27cd11f64
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #5",Eurosport 360 🇩🇪 #5
acestream://148921c4dda96df445e253d6f26c4d092bf85809
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #6" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #6",Eurosport 360 🇩🇪 #6
acestream://005ac522315699bd93bbf743329eb2f3c347dc3f
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #7" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #7",Eurosport 360 🇩🇪 #7
acestream://b18657f64507cc859cd7edef1aef90feb053e791
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #8" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #8",Eurosport 360 🇩🇪 #8
acestream://8f4f572005ca2557743474087aa622693ba9b5fe
#EXTINF:-1 tvg-id="Eurosport 360 🇩🇪 #9" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=06c72b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fes360.png" group-title="Acestream🇪🇸" tvg-name="Eurosport 360 🇩🇪 #9",Eurosport 360 🇩🇪 #9
acestream://7993cecc31917793e2bfa2fe98faa9fe1ab62d47
#EXTINF:-1 tvg-id="DAZN 1 Bar 🇩🇪" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=c3e080&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznbar01.png" group-title="Acestream🇪🇸" tvg-name="DAZN 1 Bar 🇩🇪",DAZN 1 Bar 🇩🇪
acestream://897e73c9d578848f596585314ecb9ae067c0e229
#EXTINF:-1 tvg-id="DAZN 2 Bar 🇩🇪" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=b795bf&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fdaznbar02.png" group-title="Acestream🇪🇸" tvg-name="DAZN 2 Bar 🇩🇪",DAZN 2 Bar 🇩🇪
acestream://12ea555d431dbe51fc8e4ca745aec09fe22a4865
#EXTINF:-1 tvg-id="sky sport 🇩🇪" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/3/37/Sky_Sport_2020.svg/revision/latest/scale-to-width-down/300?cb=20200911160916" group-title="Acestream🇪🇸" tvg-name="sky sport 🇩🇪",sky sport 🇩🇪
acestream://96f3385d7bd5420ffad7d54ecae5cab2b9da25c3
#EXTINF:-1 tvg-id="sport digital 🇩🇪" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/5/5b/Sport-Digital.svg/revision/latest/scale-to-width-down/250?cb=20200509224520" group-title="Acestream🇪🇸" tvg-name="sport digital 🇩🇪",sport digital 🇩🇪
acestream://5e94200ae8b1d95cb559fb150e5993d92e15d4e7
#EXTINF:-1 tvg-id="BBC ONE🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/fd/BBC_One_%282021%29.svg/revision/latest/scale-to-width-down/200?cb=20211020052725" group-title="Acestream🇪🇸" tvg-name="BBC ONE🇬🇧",BBC ONE🇬🇧
acestream://243eaccd38b9a0c43b800b6c7a30b1ad2cadc1f1
#EXTINF:-1 tvg-id="sky sports Premiere League🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/da/Sky_Sports_Premier_League_2020.svg/revision/latest/scale-to-width-down/300?cb=20200924152906" group-title="Acestream🇪🇸" tvg-name="sky sports Premiere League🇬🇧",sky sports Premiere League🇬🇧
acestream://ec5eabe0144ccfffc337e1d6708e2afb81d0638e
#EXTINF:-1 tvg-id="sky sports Football🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/fb/Sky_Sports_Football_2020.svg/revision/latest/scale-to-width-down/300?cb=20200924152526" group-title="Acestream🇪🇸" tvg-name="sky sports Football🇬🇧",sky sports Football🇬🇧
acestream://8dbe2d515e9131fa311353537736f8c94be9b26d
#EXTINF:-1 tvg-id="sky sports Main Event🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/2/2b/Sky_Sports_Main_Event_2020.svg/revision/latest/scale-to-width-down/350?cb=20200924152245" group-title="Acestream🇪🇸" tvg-name="sky sports Main Event🇬🇧",sky sports Main Event🇬🇧
acestream://eab7aeef0218ce8b0752e596e4792b69eda4df5e
#EXTINF:-1 tvg-id="sky sports Arena🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/6/6c/Sky_Sports_Arena_2020.svg/revision/latest/scale-to-width-down/300?cb=20200924152351" group-title="Acestream🇪🇸" tvg-name="sky sports Arena🇬🇧",sky sports Arena🇬🇧
acestream://d317a003e8047da2c36a2a2bb2289578c9a3b79c
#EXTINF:-1 tvg-id="PremierSports 1🇮🇪" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/a/a7/Premier_Sports_1_II.svg/revision/latest/scale-to-width-down/300?cb=20230516195441" group-title="Acestream🇪🇸" tvg-name="PremierSports 1🇮🇪",PremierSports 1🇮🇪
acestream://75a56863b6fe0407ad4305b4d7ee5643c3923565
#EXTINF:-1 tvg-id="PremierSports 2🇮🇪" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/fc/Premier_Sports_2_II.svg/revision/latest/scale-to-width-down/300?cb=20230516195653" group-title="Acestream🇪🇸" tvg-name="PremierSports 2🇮🇪",PremierSports 2🇮🇪
acestream://4903ca695edb64bc72ae29eb85a5333ba0139537
#EXTINF:-1 tvg-id="DAZN 1 🇵🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/18/DAZN_1_2024.svg/revision/latest/scale-to-width-down/300?cb=20240713213358" group-title="Acestream🇪🇸" tvg-name="DAZN 1 🇵🇹",DAZN 1 🇵🇹
acestream://36cad67fed5a739757a9db844a551aa845a8d51b
#EXTINF:-1 tvg-id="DAZN 2 🇵🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/8/82/DAZN_2_2024.svg/revision/latest/scale-to-width-down/300?cb=20240713212845" group-title="Acestream🇪🇸" tvg-name="DAZN 2 🇵🇹",DAZN 2 🇵🇹
acestream://d08013df6e437a1fdf1e0c34f573fdf6a40c7fce
#EXTINF:-1 tvg-id="DAZN 3 🇵🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/0/0f/DAZN_3_2024.svg/revision/latest/scale-to-width-down/300?cb=20240713212252" group-title="Acestream🇪🇸" tvg-name="DAZN 3 🇵🇹",DAZN 3 🇵🇹
acestream://dae7d1251f069516cc0a9c8f15f6639d2a17df1e
#EXTINF:-1 tvg-id="DAZN 4 🇵🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/f7/DAZN_4_2024.svg/revision/latest/scale-to-width-down/300?cb=20240713211915" group-title="Acestream🇪🇸" tvg-name="DAZN 4 🇵🇹",DAZN 4 🇵🇹
acestream://0f32c0131a2d9444996410801f4e18b04384db98
#EXTINF:-1 tvg-id="DAZN 5 🇵🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/b9/DAZN_5_2024.svg/revision/latest/scale-to-width-down/300?cb=20240713211021" group-title="Acestream🇪🇸" tvg-name="DAZN 5 🇵🇹",DAZN 5 🇵🇹
acestream://4dbe63b44fc4f439f5b634c0d2aa7e0cccad808a
#EXTINF:-1 tvg-id="DAZN 6 🇵🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/5/53/DAZN_6_2024.svg/revision/latest/scale-to-width-down/300?cb=20240713210829" group-title="Acestream🇪🇸" tvg-name="DAZN 6 🇵🇹",DAZN 6 🇵🇹
acestream://50b6d2b5fd59fefb9f4fd2176994d418f2b94a80
#EXTINF:-1 tvg-id="Eleven Sports 1🇵🇱" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/b/b8/Eleven_Sports_1_logo.jpg" group-title="Acestream🇪🇸" tvg-name="Eleven Sports 1🇵🇱",Eleven Sports 1🇵🇱
acestream://36cad67fed5a739757a9db844a551aa845a8d51b
#EXTINF:-1 tvg-id="sky sports 1 🇦🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/b5/Sky_Sport_Austria_1_2020.svg/revision/latest/scale-to-width-down/300?cb=20210810194821" group-title="Acestream🇪🇸" tvg-name="sky sports 1 🇦🇹",sky sports 1 🇦🇹
acestream://eec3f8107e008cec3679f76e078deeefd1348a3e
#EXTINF:-1 tvg-id="sky sports 2 🇦🇹" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/fa/Sky_Sport_Austria_2_2020.svg/revision/latest/scale-to-width-down/300?cb=20210810194354" group-title="Acestream🇪🇸" tvg-name="sky sports 2 🇦🇹",sky sports 2 🇦🇹
acestream://eec3f8107e008cec3679f76e078deeefd1348a3e
#EXTINF:-1 tvg-id="TNT Sports 1 🇬🇧" tvg-logo="https://media.info/i/lf/600/1690027797/1539.png" group-title="Acestream🇪🇸" tvg-name="TNT Sports 1 🇬🇧",TNT Sports 1 🇬🇧
acestream://fc5089d8e1519872fdf951779ccbca913acc9bce
#EXTINF:-1 tvg-id="TNT Sports 1 🇬🇧 #2" tvg-logo="https://media.info/i/lf/600/1690027797/1539.png" group-title="Acestream🇪🇸" tvg-name="TNT Sports 1 🇬🇧 #2",TNT Sports 1 🇬🇧 #2
acestream://efc60cfe5e3a349baa02bcc49f6647c21a9c3c5b
#EXTINF:-1 tvg-id="TNT Sports 2 🇬🇧" tvg-logo="https://media.info/i/lf/600/1690027877/1540.png" group-title="Acestream🇪🇸" tvg-name="TNT Sports 2 🇬🇧",TNT Sports 2 🇬🇧
acestream://d63d8a57cf471394bfa9f619bbd68b01ae27a801
#EXTINF:-1 tvg-id="TNT Sports 3 🇬🇧" tvg-logo="https://media.info/i/lf/600/1690027954/5712.png" group-title="Acestream🇪🇸" tvg-name="TNT Sports 3 🇬🇧",TNT Sports 3 🇬🇧
acestream://5f966c123759de46dff29c379266b7a403452033
#EXTINF:-1 tvg-id="TNT Sports 4 🇬🇧" tvg-logo="https://media.info/i/lf/600/1690027975/1491.png" group-title="Acestream🇪🇸" tvg-name="TNT Sports 4 🇬🇧",TNT Sports 4 🇬🇧
acestream://fc5089d8e1519872fdf951779ccbca913acc9bce
#EXTINF:-1 tvg-id="bein Sports 1🇹🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/2/27/BeinSports1.svg/revision/latest/scale-to-width-down/300?cb=20230910184457" group-title="Acestream🇪🇸" tvg-name="bein Sports 1🇹🇷",bein Sports 1🇹🇷
acestream://eb882a774ddf9f4cf83f3d50fc9a8d3c629f6659
#EXTINF:-1 tvg-id="bein Sports 1🇫🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/9/9d/BS1.svg/revision/latest/scale-to-width-down/150?cb=20200107203607" group-title="Acestream🇪🇸" tvg-name="bein Sports 1🇫🇷",bein Sports 1🇫🇷
acestream://bba1905fcd1c4975aec544047bf8e4cd23ce3fe0
#EXTINF:-1 tvg-id="bein Sports 2🇫🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/bf/BS2.svg/revision/latest/scale-to-width-down/150?cb=20200107203903" group-title="Acestream🇪🇸" tvg-name="bein Sports 2🇫🇷",bein Sports 2🇫🇷
acestream://edb507e38394d614c9ff55805c9d354ae13210bc
#EXTINF:-1 tvg-id="bein Sports 3🇫🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d8/BE_IN_SPORT_3_2017.png/revision/latest/scale-to-width-down/200?cb=20191022181110" group-title="Acestream🇪🇸" tvg-name="bein Sports 3🇫🇷",bein Sports 3🇫🇷
acestream://731bd3336ec0986ff9100efe40dbaf1473a22cf8
#EXTINF:-1 tvg-id="TV2 Sport 🇩🇰" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/0/04/TV_2_Sport_%282023%29.svg/revision/latest/scale-to-width-down/300?cb=20230327054802" group-title="Acestream🇪🇸" tvg-name="TV2 Sport 🇩🇰",TV2 Sport 🇩🇰
acestream://3b1608a6d9d4d4dff4ec660006ef1ec2f4e809ac
#EXTINF:-1 tvg-id="TV2 Sport X 🇩🇰" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d7/TV_2_Sport_X_%282023%29.svg/revision/latest/scale-to-width-down/300?cb=20230327054830" group-title="Acestream🇪🇸" tvg-name="TV2 Sport X 🇩🇰",TV2 Sport X 🇩🇰
acestream://9aa6e0e809fd88869cb7767b513cda5c422e310b
#EXTINF:-1 tvg-id="onegolf 🇵🇰" tvg-logo="https://yt3.ggpht.com/ytc/AAUvwngKBHYQfFU0i_WcTGB939gizeco3KvKlwmplNOB=s176-c-k-c0x00ffffff-no-rj" group-title="Acestream🇪🇸" tvg-name="onegolf 🇵🇰",onegolf 🇵🇰
acestream://60e1595db53c6af5339b50ad21d957ad9a44a311
#EXTINF:-1 tvg-id="SPORT·TV 1 🇵🇹" tvg-logo="https://www.lyngsat.com/logo/tv/ss/sport_tv_pt_1.png" group-title="Acestream🇪🇸" tvg-name="SPORT·TV 1 🇵🇹",SPORT·TV 1 🇵🇹
acestream://ce235921dac95e1da2dd5e54673c2fecb9e806de
#EXTINF:-1 tvg-id="SPORT·TV 2 🇵🇹" tvg-logo="https://www.lyngsat.com/logo/tv/ss/sport_tv_pt_2.png" group-title="Acestream🇪🇸" tvg-name="SPORT·TV 2 🇵🇹",SPORT·TV 2 🇵🇹
acestream://396d82ca6f5445abcd32e6b609d67e332ee12ace
#EXTINF:-1 tvg-id="SPORT·TV 3 🇵🇹" tvg-logo="https://www.lyngsat.com/logo/tv/ss/sport_tv_pt_3.png" group-title="Acestream🇪🇸" tvg-name="SPORT·TV 3 🇵🇹",SPORT·TV 3 🇵🇹
acestream://f8cb9d9e3077eb3ae417b2d95a69c5f590760eb9
#EXTINF:-1 tvg-id="SPORT·TV 4🇵🇹" tvg-logo="https://www.lyngsat.com/logo/tv/ss/sport_tv_pt_4.png" group-title="Acestream🇪🇸" tvg-name="SPORT·TV 4🇵🇹",SPORT·TV 4🇵🇹
acestream://910e1039746801860e86bd4f40ad3479f4d44af1
#EXTINF:-1 tvg-id="SPORT·TV +🇵🇹" tvg-logo="https://www.lyngsat.com/logo/tv/ss/sport_tv_pt_mais.png" group-title="Acestream🇪🇸" tvg-name="SPORT·TV +🇵🇹",SPORT·TV +🇵🇹
acestream://
#EXTINF:-1 tvg-id="SPORT·TV 5🇵🇹" tvg-logo="https://www.lyngsat.com/logo/tv/ss/sport-tv-5-pt.png" group-title="Acestream🇪🇸" tvg-name="SPORT·TV 5🇵🇹",SPORT·TV 5🇵🇹
acestream://
#EXTINF:-1 tvg-id="SPORT·TV 6🇵🇹" tvg-logo="https://www.lyngsat.com/logo/tv/ss/sport-tv-6-pt.png" group-title="Acestream🇪🇸" tvg-name="SPORT·TV 6🇵🇹",SPORT·TV 6🇵🇹
acestream://
#EXTINF:-1 tvg-id="TUDN 🇲🇽" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/f6/TUDN.svg/revision/latest/scale-to-width-down/1000?cb=20190815201557" group-title="Acestream🇪🇸" tvg-name="TUDN 🇲🇽",TUDN 🇲🇽
acestream://958a228fbcdac80a19cd3d88ef402c0e50ccca87
#EXTINF:-1 tvg-id="TUDN 🇲🇽 #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/f6/TUDN.svg/revision/latest/scale-to-width-down/1000?cb=20190815201557" group-title="Acestream🇪🇸" tvg-name="TUDN 🇲🇽 #2",TUDN 🇲🇽 #2
acestream://da68ee02776cd18de9727bb1e6eb88c3d5cbe1b2
#EXTINF:-1 tvg-id="bein Sports ñ🇺🇸" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/0/03/Bein_sports_%C3%B1_new.jpg/revision/latest/scale-to-width-down/220?cb=20170226193831" group-title="Acestream🇪🇸" tvg-name="bein Sports ñ🇺🇸",bein Sports ñ🇺🇸
acestream://e8e459656f964f601ad4bcda8b81a43ba41c68f9
#EXTINF:-1 tvg-id="bein Sports Xtra ñ🇺🇸" tvg-logo="https://beinxtraespanol.com/images/beINSPORTS-XTRA_ESPANOL-LOGO_HORIZONTAL_FULL-COLOR.png" group-title="Acestream🇪🇸" tvg-name="bein Sports Xtra ñ🇺🇸",bein Sports Xtra ñ🇺🇸
acestream://92a7dcc55392efc6dd5d012c4ff3878891eb6a6e
#EXTINF:-1 tvg-id="ESPN 🇺🇸" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/3/34/ESPN.svg/revision/latest/scale-to-width-down/300?cb=20201130040927" group-title="Acestream🇪🇸" tvg-name="ESPN 🇺🇸",ESPN 🇺🇸
acestream://4b4907de51ec11087d4bed5876f2a0c68264f442
#EXTINF:-1 tvg-id="ESPN 2 🇺🇸" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d5/ESPN2.svg/revision/latest/scale-to-width-down/318?cb=20180427153715" group-title="Acestream🇪🇸" tvg-name="ESPN 2 🇺🇸",ESPN 2 🇺🇸
acestream://664eb5fe460b96941aed633959a845b185cd8394
#EXTINF:-1 tvg-id="ESPN 🇧🇪" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/3/34/ESPN.svg/revision/latest/scale-to-width-down/300?cb=20201130040927" group-title="Acestream🇪🇸" tvg-name="ESPN 🇧🇪",ESPN 🇧🇪
acestream://79f10c6c6168e42bfc606f3f7b9e5f3ca79dedab
#EXTINF:-1 tvg-id="ESPN 2 🇧🇪" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d5/ESPN2.svg/revision/latest/scale-to-width-down/318?cb=20180427153715" group-title="Acestream🇪🇸" tvg-name="ESPN 2 🇧🇪",ESPN 2 🇧🇪
acestream://3e0ba6867173f345d482d80c771f1a5dc3b37e63
#EXTINF:-1 tvg-id="ESPN 4 🇧🇪" tvg-logo="https://static.wikia.nocookie.net/tvcable/images/c/ce/Large.1905650939_ESPN4.png.66e5580fda43eb907003d41f9d4770f4.png/revision/latest/scale-to-width-down/200?cb=20220201222409&path-prefix=es" group-title="Acestream🇪🇸" tvg-name="ESPN 4 🇧🇪",ESPN 4 🇧🇪
acestream://5f9b19c57195cc28ab81e0ec8cad03b55118687a
#EXTINF:-1 tvg-id="ESPN 🇦🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/3/34/ESPN.svg/revision/latest/scale-to-width-down/300?cb=20201130040927" group-title="Acestream🇪🇸" tvg-name="ESPN 🇦🇷",ESPN 🇦🇷
acestream://69e01491b89f60e5d68486009be753b71a0a2b01
#EXTINF:-1 tvg-id="ESPN 2 🇦🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d5/ESPN2.svg/revision/latest/scale-to-width-down/318?cb=20180427153715" group-title="Acestream🇪🇸" tvg-name="ESPN 2 🇦🇷",ESPN 2 🇦🇷
acestream://4032d916c2b1631c0ed9529faf560e11014eaeaf
#EXTINF:-1 tvg-id="ESPN 3 🇦🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/6/6c/Espn3.png/revision/latest/scale-to-width-down/250?cb=20160307235943" group-title="Acestream🇪🇸" tvg-name="ESPN 3 🇦🇷",ESPN 3 🇦🇷
acestream://517d8c2c11857d8fc92c764621dd761a9271cd60
#EXTINF:-1 tvg-id="ESPN 🇨🇴" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/3/34/ESPN.svg/revision/latest/scale-to-width-down/300?cb=20201130040927" group-title="Acestream🇪🇸" tvg-name="ESPN 🇨🇴",ESPN 🇨🇴
acestream://2492f8aa7cd7c4800e7b22c4ecba05e34c18be00
#EXTINF:-1 tvg-id="ESPN 2 🇨🇴" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d5/ESPN2.svg/revision/latest/scale-to-width-down/318?cb=20180427153715" group-title="Acestream🇪🇸" tvg-name="ESPN 2 🇨🇴",ESPN 2 🇨🇴
acestream://e40b29774fdfd953751a71f5695f647726623b9d
#EXTINF:-1 tvg-id="ESPN 3 🇨🇴" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/6/6c/Espn3.png/revision/latest/scale-to-width-down/250?cb=20160307235943" group-title="Acestream🇪🇸" tvg-name="ESPN 3 🇨🇴",ESPN 3 🇨🇴
acestream://b97f5975dbd067655432512d4693b417bc85a714
#EXTINF:-1 tvg-id="ESPN Extra 🇨🇴" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/bc/ESPN_Extra_2018.png/revision/latest/scale-to-width-down/250?cb=20220602051039&path-prefix=es" group-title="Acestream🇪🇸" tvg-name="ESPN Extra 🇨🇴",ESPN Extra 🇨🇴
acestream://9c3feb380cd9bcf9dcb7a9454ca8eb7962201612
#EXTINF:-1 tvg-id="DSports 🇦🇷" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/5/5a/DSports.png" group-title="Acestream🇪🇸" tvg-name="DSports 🇦🇷",DSports 🇦🇷
acestream://
#EXTINF:-1 tvg-id="FOX SPORTS🇦🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/7/76/FOX_Sports.svg/revision/latest/scale-to-width-down/250?cb=20180810230802" group-title="Acestream🇪🇸" tvg-name="FOX SPORTS🇦🇷",FOX SPORTS🇦🇷
acestream://d4aa975dd59ae7f4e68ceadee8b77d65e9fc1360
#EXTINF:-1 tvg-id="TyC Sports 🇦🇷" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/5/5d/TyC_Sports.svg/revision/latest/scale-to-width-down/250?cb=20100625094432" group-title="Acestream🇪🇸" tvg-name="TyC Sports 🇦🇷",TyC Sports 🇦🇷
acestream://
#EXTINF:-1 tvg-id="bein Sports 1 🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/2/27/BeinSports1.svg/revision/latest/scale-to-width-down/300?cb=20200906164016" group-title="Acestream🇪🇸" tvg-name="bein Sports 1 🇬🇧",bein Sports 1 🇬🇧
acestream://
#EXTINF:-1 tvg-id="bein Sports 2 🇬🇧" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/4/40/BeinSports2.svg/revision/latest/scale-to-width-down/220?cb=20200906164311" group-title="Acestream🇪🇸" tvg-name="bein Sports 2 🇬🇧",bein Sports 2 🇬🇧
acestream://
#EXTINF:-1 tvg-id="FS 1 🇺🇸" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/a/ad/FS1_New_Logo.svg/revision/latest/scale-to-width-down/200?cb=20161013225637" group-title="Acestream🇪🇸" tvg-name="FS 1 🇺🇸",FS 1 🇺🇸
acestream://c9c062941fbecb16ce29437f346ea7177d720898
#EXTINF:-1 tvg-id="FS 2 🇺🇸" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/e/ed/FS2_logo.svg/revision/latest/scale-to-width-down/192?cb=20170823201247" group-title="Acestream🇪🇸" tvg-name="FS 2 🇺🇸",FS 2 🇺🇸
acestream://cba8d369eac629b577750edb90370cd1c5fb03b7
#EXTINF:-1 tvg-id="NBA TV 🇺🇸" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/1a/NBA_TV_2017.svg/revision/latest/scale-to-width-down/200?cb=20171022122312" group-title="Acestream🇪🇸" tvg-name="NBA TV 🇺🇸",NBA TV 🇺🇸
acestream://e72d03fb9694164317260f684470be9ab781ed95
#EXTINF:-1 tvg-id="NBA TV 🇺🇸 #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/1a/NBA_TV_2017.svg/revision/latest/scale-to-width-down/200?cb=20171022122312" group-title="Acestream🇪🇸" tvg-name="NBA TV 🇺🇸 #2",NBA TV 🇺🇸 #2
acestream://c8aac540621d481965791c4442a7e868bcca10ca
#EXTINF:-1 tvg-id="NBA Network 🇺🇸" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/1a/NBA_TV_2017.svg/revision/latest/scale-to-width-down/200?cb=20171022122312" group-title="Acestream🇪🇸" tvg-name="NBA Network 🇺🇸",NBA Network 🇺🇸
acestream://6ad33feec75d929de54d77b9becfe767ae83fcb3
#EXTINF:-1 tvg-id="UFC TV" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/d/d6/Ultimate_Fighting_Championship.svg/revision/latest/scale-to-width-down/200?cb=20160901192708" group-title="Acestream🇪🇸" tvg-name="UFC TV",UFC TV
acestream://f74dcf44f57fc71cb4b0719b3342e569eba50c51
#EXTINF:-1 tvg-id="Copa por M+" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MCOPA.png" group-title="Acestream🇪🇸" tvg-name="Copa por M+",Copa por M+
acestream://b51f2d9a15b6956a44385b6be531bcabeb099d9d
#EXTINF:-1 tvg-id="1RFEF 1" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/2/23/Logo_Primera_RFEF.jpg" group-title="Acestream🇪🇸" tvg-name="1RFEF 1",1RFEF 1
acestream://c1ee6e1e0ef5928d8261f855c417de21794f437d
#EXTINF:-1 tvg-id="1RFEF 2" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/2/23/Logo_Primera_RFEF.jpg" group-title="Acestream🇪🇸" tvg-name="1RFEF 2",1RFEF 2
acestream://8677d339ecddd75165c0015025f598b6215974cf
#EXTINF:-1 tvg-id="DAZN LaLiga 2" tvg-logo="https://telegra.ph/file/94036fc98a0d900cc62a5.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga 2",DAZN LaLiga 2
acestream://635b61c1f240449163260cd914d10d886a54fee3
#EXTINF:-1 tvg-id="DAZN LaLiga 2 #2" tvg-logo="https://telegra.ph/file/94036fc98a0d900cc62a5.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga 2 #2",DAZN LaLiga 2 #2
acestream://ae16a8f004b1287ee1f53263ab265f72bba0daf5
#EXTINF:-1 tvg-id="DAZN LaLiga 2 #3" tvg-logo="https://telegra.ph/file/94036fc98a0d900cc62a5.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga 2 #3",DAZN LaLiga 2 #3
acestream://a231b2fa1f7754433efeb8bb8d69d7b9096dcba8
#EXTINF:-1 tvg-id="DAZN LaLiga 2 #4" tvg-logo="https://telegra.ph/file/94036fc98a0d900cc62a5.jpg" group-title="Acestream🇪🇸" tvg-name="DAZN LaLiga 2 #4",DAZN LaLiga 2 #4
acestream://c976c7b37964322752db562b4ad65515509c8d36
#EXTINF:-1 tvg-id="M+ LaLiga 2" tvg-logo="https://telegra.ph/file/954f096c5f1cb382e50f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 2",M+ LaLiga 2
acestream://51b363b1c4d42724e05240ad068ad219df8042ec
#EXTINF:-1 tvg-id="M+ LaLiga 2 #2" tvg-logo="https://telegra.ph/file/954f096c5f1cb382e50f7.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 2 #2",M+ LaLiga 2 #2
acestream://ad42faa399df66dcd62a1cbc9d1c99ed4512d3b8
#EXTINF:-1 tvg-id="M+ LaLiga 3" tvg-logo="https://telegra.ph/file/d9a9b3f25fff3ffff3ab5.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 3",M+ LaLiga 3
acestream://7ad14386deef2f45ffe17d30a631dbf79b6a1a87
#EXTINF:-1 tvg-id="M+ LaLiga 3 #2" tvg-logo="https://telegra.ph/file/d9a9b3f25fff3ffff3ab5.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 3 #2",M+ LaLiga 3 #2
acestream://382b14499e3d76e557d449d2e5bbc4e4bd63bd39
#EXTINF:-1 tvg-id="M+ LaLiga 4" tvg-logo="https://telegra.ph/file/dbf9f93a95f2e1d732098.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 4",M+ LaLiga 4
acestream://68697ea4f261289d97bbc3418ad3cbc4180aa32f
#EXTINF:-1 tvg-id="M+ LaLiga 5" tvg-logo="https://telegra.ph/file/2bf2e508d5e905203eae0.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 5",M+ LaLiga 5
acestream://535394f62a810bc5aeb25be75ea5ff7d03e070b2
#EXTINF:-1 tvg-id="M+ LaLiga 6" tvg-logo="https://telegra.ph/file/1beb547ed9a6f41b3aabc.jpg" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 6",M+ LaLiga 6
acestream://c896d37778f9e43549a788fc22206a655895b51b
#EXTINF:-1 tvg-id="M+ LaLiga 7" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIG6.png" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 7",M+ LaLiga 7
acestream://
#EXTINF:-1 tvg-id="M+ LaLiga 8" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIG7.png" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 8",M+ LaLiga 8
acestream://
#EXTINF:-1 tvg-id="M+ LaLiga 9" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIG8.png" group-title="Acestream🇪🇸" tvg-name="M+ LaLiga 9",M+ LaLiga 9
acestream://
#EXTINF:-1 tvg-id="LaLiga Hypermotion 2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS2.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 2",LaLiga Hypermotion 2
acestream://709075831bf5c41ed0a20dfbd640aab6c28971f8
#EXTINF:-1 tvg-id="LaLiga Hypermotion 2 #2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS2.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 2 #2",LaLiga Hypermotion 2 #2
acestream://0a335406bad0b658aeddb2d38f8c0614b2e5623a
#EXTINF:-1 tvg-id="LaLiga Hypermotion 3" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS3.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 3",LaLiga Hypermotion 3
acestream://778d2f60bb7207addedcca0b9aed98f41529724e
#EXTINF:-1 tvg-id="LaLiga Hypermotion 4" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS4.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 4",LaLiga Hypermotion 4
acestream://9bbbaec25775a0c47b07ceb547fe5e017c169729
#EXTINF:-1 tvg-id="LaLiga Hypermotion 5" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS5.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 5",LaLiga Hypermotion 5
acestream://8656b8874dbb8f52911ca0ad6e1e3d177526508f
#EXTINF:-1 tvg-id="LaLiga Hypermotion 6" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MLIGS6.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 6",LaLiga Hypermotion 6
acestream://7a9bb1b9cccb759c44ed84f3c1283922e6854670
#EXTINF:-1 tvg-id="LaLiga Hypermotion 7" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/DAZNL5.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 7",LaLiga Hypermotion 7
acestream://446e73a22582921393b020ed08b768ad8e14d754
#EXTINF:-1 tvg-id="LaLiga Hypermotion 8" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/DAZNL5.png" group-title="Acestream🇪🇸" tvg-name="LaLiga Hypermotion 8",LaLiga Hypermotion 8
acestream://4d52fc1994fe927702aeb7bc8778e2f23b1260e2
#EXTINF:-1 tvg-id="M+ Liga de Campeones 4" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=2d0575&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc4.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 4",M+ Liga de Campeones 4
acestream://77998f8161373611ff6b348e7eda5b4e97d3ec29
#EXTINF:-1 tvg-id="M+ Liga de Campeones 4 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=2d0575&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc4.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 4 #2",M+ Liga de Campeones 4 #2
acestream://f1219582a3059e7fff2db22e69475c45cbc84356
#EXTINF:-1 tvg-id="M+ Liga de Campeones 5" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=c6b10d&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc5.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 5",M+ Liga de Campeones 5
acestream://cb6410a6355a645cfc6f6f5a7c7d71298fcbc2c5
#EXTINF:-1 tvg-id="M+ Liga de Campeones 5 #2" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=c6b10d&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc5.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 5 #2",M+ Liga de Campeones 5 #2
acestream://d2cf12b65c8a540a50bd74c3db1ce59ae8d05623
#EXTINF:-1 tvg-id="M+ Liga de Campeones 6" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=75b4af&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc6.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 6",M+ Liga de Campeones 6
acestream://976983697790ab8a07b764b08843529d38bc6444
#EXTINF:-1 tvg-id="M+ Liga de Campeones 7" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=531aa9&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc7.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 7",M+ Liga de Campeones 7
acestream://83c02982581a536d1321e38a77dc0c520b1cb842
#EXTINF:-1 tvg-id="M+ Liga de Campeones 8" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=6a2778&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc8.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 8",M+ Liga de Campeones 8
acestream://97f8a84212fe6b3d2ab15aadc83c7b5e6af656c9
#EXTINF:-1 tvg-id="M+ Liga de Campeones 9" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=b65ff5&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc9.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 9",M+ Liga de Campeones 9
acestream://80abcb38122c25fefb4dffeb57086998447ff49b
#EXTINF:-1 tvg-id="M+ Liga de Campeones 10" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=3c2c9b&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc10.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 10",M+ Liga de Campeones 10
acestream://0103373118989085dd0d02667c629ee36d462cb1
#EXTINF:-1 tvg-id="M+ Liga de Campeones 11" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=509395&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc11.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 11",M+ Liga de Campeones 11
acestream://6e12a5849a4edea248ed9c8689e58bd66fc9f8fa
#EXTINF:-1 tvg-id="M+ Liga de Campeones 12" tvg-logo="https://www.mundoplus.tv/wiki/lib/exe/fetch.php?w=144&h=108&tok=0d49be&media=https%3A%2F%2Fwww.mundoplus.tv%2Fwiki%2F_media%2Flogos%2Fmlc12.png" group-title="Acestream🇪🇸" tvg-name="M+ Liga de Campeones 12",M+ Liga de Campeones 12
acestream://130d37f9a68bd8f29f0d636dcde522a1e91d1cb7
#EXTINF:-1 tvg-id="DAZN Liga F 1" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Liga_F_2022_Logo.svg/1920px-Liga_F_2022_Logo.svg.png" group-title="Acestream🇪🇸" tvg-name="DAZN Liga F 1",DAZN Liga F 1
acestream://600222a4f98df80a2c0df2d60cb5ff3df9620710
#EXTINF:-1 tvg-id="DAZN Liga F 2" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Liga_F_2022_Logo.svg/1920px-Liga_F_2022_Logo.svg.png" group-title="Acestream🇪🇸" tvg-name="DAZN Liga F 2",DAZN Liga F 2
acestream://d6cdd724a97fcf851e7ef641c28d6beb8663496e
#EXTINF:-1 tvg-id="DAZN Liga F 3" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Liga_F_2022_Logo.svg/1920px-Liga_F_2022_Logo.svg.png" group-title="Acestream🇪🇸" tvg-name="DAZN Liga F 3",DAZN Liga F 3
acestream://162942adc047d0f78eac056effbe5bbec54a5e51
#EXTINF:-1 tvg-id="DAZN Liga F 4" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Liga_F_2022_Logo.svg/1920px-Liga_F_2022_Logo.svg.png" group-title="Acestream🇪🇸" tvg-name="DAZN Liga F 4",DAZN Liga F 4
acestream://e454681a152a86da504e63694f17f90d0586867d
#EXTINF:-1 tvg-id="Gol Mundial #1" tvg-logo="https://pbs.twimg.com/profile_images/1693747769851232257/meLYo2BI_400x400.jpg" group-title="Acestream🇪🇸" tvg-name="Gol Mundial #1",Gol Mundial #1
acestream://78384a676407784df944243eb2f75d937fbcc253
#EXTINF:-1 tvg-id="Gol Mundial #2" tvg-logo="https://pbs.twimg.com/profile_images/1693747769851232257/meLYo2BI_400x400.jpg" group-title="Acestream🇪🇸" tvg-name="Gol Mundial #2",Gol Mundial #2
acestream://4af5952b95d3c2e99fcdc0de2f528d3fcd73e06b
#EXTINF:-1 tvg-id="Gol Mundial #3" tvg-logo="https://pbs.twimg.com/profile_images/1693747769851232257/meLYo2BI_400x400.jpg" group-title="Acestream🇪🇸" tvg-name="Gol Mundial #3",Gol Mundial #3
acestream://52c8ff01836c294caad8b8c029b53360aa16a4cd
#EXTINF:-1 tvg-id="Gol Mundial #4" tvg-logo="https://pbs.twimg.com/profile_images/1693747769851232257/meLYo2BI_400x400.jpg" group-title="Acestream🇪🇸" tvg-name="Gol Mundial #4",Gol Mundial #4
acestream://5a8d60f4c8e558f8ae5acad7c75f455928ce0c2e
#EXTINF:-1 tvg-id="Movistar Plus+" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Movistar Acestream🇪🇸" tvg-name="Movistar Plus+",Movistar Plus+
acestream://8c67cdb5ba81976662c3a67984a9545d9cfb0f70
#EXTINF:-1 tvg-id="Movistar Plus+ #2" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Movistar Acestream🇪🇸" tvg-name="Movistar Plus+ #2",Movistar Plus+ #2
acestream://b6ffbbc72a5b6b579faf79ebac229af7a25b933b
#EXTINF:-1 tvg-id="Movistar Plus+ #3" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Movistar Acestream🇪🇸" tvg-name="Movistar Plus+ #3",Movistar Plus+ #3
acestream://5d9a26e0a5f3e5f2ae027bd05635ab9a4fd4b51a
#EXTINF:-1 tvg-id="Movistar Plus+ #4" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Movistar Acestream🇪🇸" tvg-name="Movistar Plus+ #4",Movistar Plus+ #4
acestream://5e24a1b9187fccb91553f7c7da4b36341386f74a
#EXTINF:-1 tvg-id="Movistar Plus+ #5" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Movistar Acestream🇪🇸" tvg-name="Movistar Plus+ #5",Movistar Plus+ #5
acestream://56ac8e227d526e722624675ccdd91b0cc850582f
#EXTINF:-1 tvg-id="Movistar Plus+ #6" tvg-logo="https://images.seeklogo.com/logo-png/42/1/movistar-plus-logo-png_seeklogo-426538.png" group-title="Movistar Acestream🇪🇸" tvg-name="Movistar Plus+ #6",Movistar Plus+ #6
acestream://1ab443f5b4beb6d586f19e8b25b9f9646cf2ab78
#EXTINF:-1 tvg-id="Movistar Plus+ 2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/MPLUS2.png" group-title="Movistar Acestream🇪🇸" tvg-name="Movistar Plus+ 2",Movistar Plus+ 2
acestream://fbc39d8a9e5d7c9ac6a1438d440104620f54e09c
#EXTINF:-1 tvg-id="Estrenos por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MV1.png" group-title="Movistar Acestream🇪🇸" tvg-name="Estrenos por M+",Estrenos por M+
acestream://6341392460596e63edf38b013bd137c015e44007
#EXTINF:-1 tvg-id="Estrenos por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MV1.png" group-title="Movistar Acestream🇪🇸" tvg-name="Estrenos por M+ #2",Estrenos por M+ #2
acestream://b71478c824f787a6a696139db0d053de6fdd1d38
#EXTINF:-1 tvg-id="Hits por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MHITS.png" group-title="Movistar Acestream🇪🇸" tvg-name="Hits por M+",Hits por M+
acestream://2752dee68a7faa9c847216dc22a6821661db891a
#EXTINF:-1 tvg-id="Hits por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MHITS.png" group-title="Movistar Acestream🇪🇸" tvg-name="Hits por M+ #2",Hits por M+ #2
acestream://2b8e5c7438d56541df3467cc5986cf1e66014101
#EXTINF:-1 tvg-id="Hits por M+ #3" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MHITS.png" group-title="Movistar Acestream🇪🇸" tvg-name="Hits por M+ #3",Hits por M+ #3
acestream://28b9b7ba12c0f5c7e097f4b07a547f6eda9a0695
#EXTINF:-1 tvg-id="Documentales por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MDOC.png" group-title="Movistar Acestream🇪🇸" tvg-name="Documentales por M+",Documentales por M+
acestream://6cda7d2622bcafd6aef486016238936855927d7d
#EXTINF:-1 tvg-id="Documentales por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MDOC.png" group-title="Movistar Acestream🇪🇸" tvg-name="Documentales por M+ #2",Documentales por M+ #2
acestream://59d7f6da13c21652b1240578fe57dec0cc1529e6
#EXTINF:-1 tvg-id="Originales por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MORIG.png" group-title="Movistar Acestream🇪🇸" tvg-name="Originales por M+",Originales por M+
acestream://1f092144252939810fd302cbd00d46de760b5dd7
#EXTINF:-1 tvg-id="Originales por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MORIG.png" group-title="Movistar Acestream🇪🇸" tvg-name="Originales por M+ #2",Originales por M+ #2
acestream://60fcd59471ac4268e6cd6448f068a2b518841c88
#EXTINF:-1 tvg-id="Cine Español por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/DCESP.png" group-title="Movistar Acestream🇪🇸" tvg-name="Cine Español por M+",Cine Español por M+
acestream://e47cdeba9d919d6a9b4fa3c72c8094178985f668
#EXTINF:-1 tvg-id="Cine Español por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/DCESP.png" group-title="Movistar Acestream🇪🇸" tvg-name="Cine Español por M+ #2",Cine Español por M+ #2
acestream://168ad4a958aa6daa26adeee9700ed0312618bd07
#EXTINF:-1 tvg-id="Vacaciones por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MVCIVA.png" group-title="Movistar Acestream🇪🇸" tvg-name="Vacaciones por M+",Vacaciones por M+
acestream://15123ab3458c59bf548fbf6e5503799e81da4de6
#EXTINF:-1 tvg-id="Vacaciones por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MVCIVA.png" group-title="Movistar Acestream🇪🇸" tvg-name="Vacaciones por M+ #2",Vacaciones por M+ #2
acestream://a0f71ac4897b2ccdf0114b5b3b7877902376a343
#EXTINF:-1 tvg-id="WÉSTERN por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MWEST.png" group-title="Movistar Acestream🇪🇸" tvg-name="WÉSTERN por M+",WÉSTERN por M+
acestream://e740a34497c3ba5943613a06999e805e6bbfa159
#EXTINF:-1 tvg-id="WÉSTERN por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MWEST.png" group-title="Movistar Acestream🇪🇸" tvg-name="WÉSTERN por M+ #2",WÉSTERN por M+ #2
acestream://860dd021db341dbd02979eb8ea650d3f9d846765
#EXTINF:-1 tvg-id="Indie por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MINDI.png" group-title="Movistar Acestream🇪🇸" tvg-name="Indie por M+",Indie por M+
acestream://508ffdbab097339adb4f3d922070b5df2c114d01
#EXTINF:-1 tvg-id="Indie por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MINDI.png" group-title="Movistar Acestream🇪🇸" tvg-name="Indie por M+ #2",Indie por M+ #2
acestream://4f35f115971f0b156baabb8efa9926b1eb8ba5af
#EXTINF:-1 tvg-id="Acción por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CPACCI.png" group-title="Movistar Acestream🇪🇸" tvg-name="Acción por M+",Acción por M+
acestream://102bcb79ca391e37ac1fc9ee77dc53440d0a59ce
#EXTINF:-1 tvg-id="Acción por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CPACCI.png" group-title="Movistar Acestream🇪🇸" tvg-name="Acción por M+ #2",Acción por M+ #2
acestream://b125325f52e057b8e5ea17a8b60d512d13d44e53
#EXTINF:-1 tvg-id="Acción por M+ #3" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CPACCI.png" group-title="Movistar Acestream🇪🇸" tvg-name="Acción por M+ #3",Acción por M+ #3
acestream://93b2f5ede5cf2fa0cdb50419258c4f651aabfc42
#EXTINF:-1 tvg-id="Comedia por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CPCOME.png" group-title="Movistar Acestream🇪🇸" tvg-name="Comedia por M+",Comedia por M+
acestream://90a3ad526f67f987f662eaf7d52e88004c796914
#EXTINF:-1 tvg-id="Comedia por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CPCOME.png" group-title="Movistar Acestream🇪🇸" tvg-name="Comedia por M+ #2",Comedia por M+ #2
acestream://124aa6d58fd72a763ed0349c874551bd2504798f
#EXTINF:-1 tvg-id="Drama por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CPCOLE.png" group-title="Movistar Acestream🇪🇸" tvg-name="Drama por M+",Drama por M+
acestream://edee311dc307e1638eeac880b11bb6f4759b0d83
#EXTINF:-1 tvg-id="Drama por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CPCOLE.png" group-title="Movistar Acestream🇪🇸" tvg-name="Drama por M+ #2",Drama por M+ #2
acestream://aff9d7e45c4fc0f97ec8ec2b6d80cd3feb87c983
#EXTINF:-1 tvg-id="Clásicos por M+" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MCLAS.png" group-title="Movistar Acestream🇪🇸" tvg-name="Clásicos por M+",Clásicos por M+
acestream://cf6ffdfa3c51268c0bd216da6b275fb866160c0c
#EXTINF:-1 tvg-id="Clásicos por M+ #2" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MCLAS.png" group-title="Movistar Acestream🇪🇸" tvg-name="Clásicos por M+ #2",Clásicos por M+ #2
acestream://f9d431a6839e7f9964a0884dc1f18d298d990f39
#EXTINF:-1 tvg-id="Clásicos por M+ #3" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/MCLAS.png" group-title="Movistar Acestream🇪🇸" tvg-name="Clásicos por M+ #3",Clásicos por M+ #3
acestream://095134586cd06e1488139842f1183b50b75f5fd1
#EXTINF:-1 tvg-id="Cocina" tvg-logo="https://mir-s3-cdn-cf.behance.net/projects/404/21568331328673.Y3JvcCw5MDAsNzAzLDAsNDU.png" group-title="Movistar Acestream🇪🇸" tvg-name="Cocina",Cocina
acestream://db81615f1b2eebaf584edc252ddd73883123fbb3
#EXTINF:-1 tvg-id="Cocina #2" tvg-logo="https://mir-s3-cdn-cf.behance.net/projects/404/21568331328673.Y3JvcCw5MDAsNzAzLDAsNDU.png" group-title="Movistar Acestream🇪🇸" tvg-name="Cocina #2",Cocina #2
acestream://96f092e1fa99062f6da14cae230b877ad3ed849b
#EXTINF:-1 tvg-id="Nat Geo" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/NATGEO.png" group-title="Movistar Acestream🇪🇸" tvg-name="Nat Geo",Nat Geo
acestream://55230a7a3cc4e8dfd3cecbfb2d68266aa4e5dfff
#EXTINF:-1 tvg-id="Nat Geo Wild" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/NATGW.png" group-title="Movistar Acestream🇪🇸" tvg-name="Nat Geo Wild",Nat Geo Wild
acestream://51d0b5249e229a07ecc52286f56a67c3d9df6d00
#EXTINF:-1 tvg-id="Caza y Pesca" tvg-logo="https://www.movistarplus.es/recorte/m-DPBLAN/guiamovil/CAZPES.png" group-title="Movistar Acestream🇪🇸" tvg-name="Caza y Pesca",Caza y Pesca
acestream://6f28b1b9eb9f4047a6179b300e65b03c8316e10f
#EXTINF:-1 tvg-id="One Toro" tvg-logo="https://onetoro.tv/assets/icon/Logotipo.svg" group-title="Movistar Acestream🇪🇸" tvg-name="One Toro",One Toro
acestream://cd0188292b6b3876ff66c99bd3d25eab88b41079
#EXTINF:-1 tvg-id="One Toro #2" tvg-logo="https://onetoro.tv/assets/icon/Logotipo.svg" group-title="Movistar Acestream🇪🇸" tvg-name="One Toro #2",One Toro #2
acestream://1fd3dbb7d39de875ac70059d70c8768d4a2e43c0
#EXTINF:-1 tvg-id="La 1" tvg-logo="https://i.ibb.co/swhGnw4/La1.jpg" group-title="TDT Acestream🇪🇸" tvg-name="La 1",La 1
acestream://dad5e0e0825cb3e410008f1c4252387b868e740c
#EXTINF:-1 tvg-id="La 2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/LA2.png" group-title="TDT Acestream🇪🇸" tvg-name="La 2",La 2
acestream://9934906503661142f97a044ae1509a294057c2ed
#EXTINF:-1 tvg-id="Antena 3" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/A3.png" group-title="TDT Acestream🇪🇸" tvg-name="Antena 3",Antena 3
acestream://f9d2a6d5da8d1f2423a0b6ed0047636a728040e9
#EXTINF:-1 tvg-id="cuatro" tvg-logo="https://i.ibb.co/FJch0Y9/Cuatro.jpg" group-title="TDT Acestream🇪🇸" tvg-name="cuatro",cuatro
acestream://8d66979e705a8b532b9243bbc0862c0f1c734ef0
#EXTINF:-1 tvg-id="cuatro #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/c/ce/Cuatro.svg/revision/latest/scale-to-width-down/300?cb=20181124123341" group-title="TDT Acestream🇪🇸" tvg-name="cuatro #2",cuatro #2
acestream://8670df538a11c6ec97b3f634981ddc4409ca0333
#EXTINF:-1 tvg-id="Telecinco" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/T5.png" group-title="TDT Acestream🇪🇸" tvg-name="Telecinco",Telecinco
acestream://5133d1e8f45095f0b7dabbd78db0ce19a496f7bf
#EXTINF:-1 tvg-id="Telecinco #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/f/fc/Telecinco.svg/revision/latest/scale-to-width-down/150?cb=20120312235721" group-title="TDT Acestream🇪🇸" tvg-name="Telecinco #2",Telecinco #2
acestream://3e7b1911a1f83fd869b6995650a3057778259ca7
#EXTINF:-1 tvg-id="Telecinco #3" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/T5.png" group-title="TDT Acestream🇪🇸" tvg-name="Telecinco #3",Telecinco #3
acestream://3d376333ee90d6db3d413fc5764ef635882076f5
#EXTINF:-1 tvg-id="lasexta" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/SEXTA.png" group-title="TDT Acestream🇪🇸" tvg-name="lasexta",lasexta
acestream://44828a7580cd99fcb36245c327889c47f34b457f
#EXTINF:-1 tvg-id="tdp" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/TDEP.png" group-title="TDT Acestream🇪🇸" tvg-name="tdp",tdp
acestream://138b30c93e8a780ac490a4f6d2181c41f3670230
#EXTINF:-1 tvg-id="tdp #2" tvg-logo="https://i.ibb.co/thh1tKH/TDP.jpg" group-title="TDT Acestream🇪🇸" tvg-name="tdp #2",tdp #2
acestream://bdc32e0f99653f96e0e1a3b98c88764b631ed9ef
#EXTINF:-1 tvg-id="Gol Play" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOL.png" group-title="TDT Acestream🇪🇸" tvg-name="Gol Play",Gol Play
acestream://b2d560741c006fc5e4a42412bb52dbd25a6a4a3a
#EXTINF:-1 tvg-id="Gol Play #2" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOL.png" group-title="TDT Acestream🇪🇸" tvg-name="Gol Play #2",Gol Play #2
acestream://9fb99c40a2c45d5c5342b30626eb56140f980612
#EXTINF:-1 tvg-id="Gol Play #3" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOL.png" group-title="TDT Acestream🇪🇸" tvg-name="Gol Play #3",Gol Play #3
acestream://73094658f0a3ed523c0e188de67a7a690c0d4f93
#EXTINF:-1 tvg-id="Gol Play #4" tvg-logo="https://www.movistarplus.es/recorte/m-NEO/canal/GOL.png" group-title="TDT Acestream🇪🇸" tvg-name="Gol Play #4",Gol Play #4
acestream://472d1f3a658a51bcab0ffa9138e1e28a05fba30b
#EXTINF:-1 tvg-id="mega" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/6/61/Mega_Spain_2015.svg/revision/latest/scale-to-width-down/250?cb=20200629082553" group-title="TDT Acestream🇪🇸" tvg-name="mega",mega
acestream://5c02eda19460d039aee54b6cdfd89ec5b0b9e1f2
#EXTINF:-1 tvg-id="BE MAD" tvg-logo="https://i.ibb.co/2qxWsCP/BeMad.jpg" group-title="TDT Acestream🇪🇸" tvg-name="BE MAD",BE MAD
acestream://5c267a00f264736c1d47c1cc3e754447ca8f770c
#EXTINF:-1 tvg-id="TVG2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/11/G2_logo.png/revision/latest/scale-to-width-down/200?cb=20120428192217" group-title="TDT Acestream🇪🇸" tvg-name="TVG2",TVG2
acestream://423bc5679e0e0b8f5558489dcfe5b2cf13a1ee33
#EXTINF:-1 tvg-id="TVG2 #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/11/G2_logo.png/revision/latest/scale-to-width-down/200?cb=20120428192217" group-title="TDT Acestream🇪🇸" tvg-name="TVG2 #2",TVG2 #2
acestream://b0828fed32b7a075d884fede4aad2d41493d6a0b
#EXTINF:-1 tvg-id="TVG2 #3" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/11/G2_logo.png/revision/latest/scale-to-width-down/200?cb=20120428192217" group-title="TDT Acestream🇪🇸" tvg-name="TVG2 #3",TVG2 #3
acestream://143acba630079a28de3e51d096bf3a2b422e691b
#EXTINF:-1 tvg-id="TVG2 #4" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/1/11/G2_logo.png/revision/latest/scale-to-width-down/200?cb=20120428192217" group-title="TDT Acestream🇪🇸" tvg-name="TVG2 #4",TVG2 #4
acestream://4b10fe7a9fd47e3fcf572b2186ce2b2de7823a09
#EXTINF:-1 tvg-id="Realmadrid TV" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/9/91/RM2019.png/revision/latest/scale-to-width-down/180?cb=20191224175551" group-title="TDT Acestream🇪🇸" tvg-name="Realmadrid TV",Realmadrid TV
acestream://0827cf7d290967985892965c6e61244a479d6dcd
#EXTINF:-1 tvg-id="Realmadrid TV #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/9/91/RM2019.png/revision/latest/scale-to-width-down/180?cb=20191224175551" group-title="TDT Acestream🇪🇸" tvg-name="Realmadrid TV #2",Realmadrid TV #2
acestream://0ec3f3786318acd8dca2588f74c3759cda76cd11
#EXTINF:-1 tvg-id="Canal Sur" tvg-logo="https://brandemia.org/contenido/subidas/2011/03/02-cnala-sur-estrena-identidad-grafica.jpg" group-title="TDT Acestream🇪🇸" tvg-name="Canal Sur",Canal Sur
acestream://4340f8b4726bedadbc2bd0d137cf3b4f6afa40ef
#EXTINF:-1 tvg-id="esport 3" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/5/54/Esport3_logo2011-578x430.png/revision/latest/scale-to-width-down/578?cb=20200602193535&path-prefix=es" group-title="TDT Acestream🇪🇸" tvg-name="esport 3",esport 3
acestream://181fcc443b953d54b00a1bf6320ccbb097e85d64
#EXTINF:-1 tvg-id="esport 3 #2" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/5/54/Esport3_logo2011-578x430.png/revision/latest/scale-to-width-down/578?cb=20200602193535&path-prefix=es" group-title="TDT Acestream🇪🇸" tvg-name="esport 3 #2",esport 3 #2
acestream://ca20f93ea5d9c15744e48a21b52598b9fce87425
#EXTINF:-1 tvg-id="Napoleón" tvg-logo="https://pics.filmaffinity.com/napoleon-425552994-large.jpg" group-title="Películas" tvg-name="Napoleón",Napoleón
acestream://9a6a0bf17dd15aea190f509599dd92bf4cd68ddd
#EXTINF:-1 tvg-id="La Sociedad de la Nieve" tvg-logo="https://pics.filmaffinity.com/la_sociedad_de_la_nieve-376125816-large.jpg" group-title="Películas" tvg-name="La Sociedad de la Nieve",La Sociedad de la Nieve
acestream://9274396dff8a14a65a092951004f28b37b14aa0c
#EXTINF:-1 tvg-id="Los Asesinos de la Luna" tvg-logo="https://pics.filmaffinity.com/killers_of_the_flower_moon-364025498-large.jpg" group-title="Películas" tvg-name="Los Asesinos de la Luna",Los Asesinos de la Luna
acestream://8b1df56b8d66300de36c4ce86be87ebc7ea8bfa8
#EXTINF:-1 tvg-id="Oppenheimer" tvg-logo="https://pics.filmaffinity.com/oppenheimer-457985394-large.jpg" group-title="Películas" tvg-name="Oppenheimer",Oppenheimer
acestream://f25be9cf261dd77b95c6bfccfcead2ff73053a87
#EXTINF:-1 tvg-id="El Asesino" tvg-logo="https://pics.filmaffinity.com/the_killer-609845433-large.jpg" group-title="Películas" tvg-name="El Asesino",El Asesino
acestream://1f4e295c76c2cfd6d940ad11ed29208896907b28
#EXTINF:-1 tvg-id="Misterio en Venecia" tvg-logo="https://pics.filmaffinity.com/a_haunting_in_venice-242356419-large.jpg" group-title="Películas" tvg-name="Misterio en Venecia",Misterio en Venecia
acestream://4653278b16a10789237941d569b8e38ffa434e94
#EXTINF:-1 tvg-id="Misterio en Venecia #2" tvg-logo="https://pics.filmaffinity.com/a_haunting_in_venice-242356419-large.jpg" group-title="Películas" tvg-name="Misterio en Venecia #2",Misterio en Venecia #2
acestream://9c31983a73f2f058ee21eece789226baa3b885d2
#EXTINF:-1 tvg-id="Indiana Jones y el Dial del Destino" tvg-logo="https://pics.filmaffinity.com/indiana_jones_and_the_dial_of_destiny-877605954-large.jpg" group-title="Películas" tvg-name="Indiana Jones y el Dial del Destino",Indiana Jones y el Dial del Destino
acestream://eae1710c22b8605215afc2516c519d21654cc821
#EXTINF:-1 tvg-id="Misión imposible: Sentencia mortal (Parte 1)" tvg-logo="https://pics.filmaffinity.com/mission_impossible_dead_reckoning_part_one-595394181-large.jpg" group-title="Películas" tvg-name="Misión imposible: Sentencia mortal (Parte 1)",Misión imposible: Sentencia mortal (Parte 1)
acestream://59aaacdb6d3dd51fba6d0306752f1549bbb947ef
#EXTINF:-1 tvg-id="Misión imposible: Sentencia mortal (Parte 1) #2" tvg-logo="https://pics.filmaffinity.com/mission_impossible_dead_reckoning_part_one-595394181-large.jpg" group-title="Películas" tvg-name="Misión imposible: Sentencia mortal (Parte 1) #2",Misión imposible: Sentencia mortal (Parte 1) #2
acestream://08647c73c127c4996bb792e96214a15d4752624c
#EXTINF:-1 tvg-id="El Arte de Matar" tvg-logo="https://pics.filmaffinity.com/the_kill_room-468791574-large.jpg" group-title="Películas" tvg-name="El Arte de Matar",El Arte de Matar
acestream://9b8482566b81554c494cb3350337284f1a04ebaf
#EXTINF:-1 tvg-id="Barbie" tvg-logo="https://pics.filmaffinity.com/barbie-321648337-large.jpg" group-title="Películas" tvg-name="Barbie",Barbie
acestream://bb34a8a08c2305375a65d4019c4e471af7433347
#EXTINF:-1 tvg-id="The Burial" tvg-logo="https://pics.filmaffinity.com/the_burial-643723780-large.jpg" group-title="Películas" tvg-name="The Burial",The Burial
acestream://bbde8b23e7e1a3fd62e6bdd46360c4400b5c6c7b
#EXTINF:-1 tvg-id="Shin Ultraman" tvg-logo="https://pics.filmaffinity.com/shin_ultraman-825522223-large.jpg" group-title="Películas" tvg-name="Shin Ultraman",Shin Ultraman
acestream://c0ba459614d42a282bb72c16b018b1ea4319bd34
#EXTINF:-1 tvg-id="Asteroid City" tvg-logo="https://pics.filmaffinity.com/asteroid_city-213090918-large.jpg" group-title="Películas" tvg-name="Asteroid City",Asteroid City
acestream://2f702a2b4aff20f7e542ad281f503ddd9f72c38c
#EXTINF:-1 tvg-id="Fast & Furious X" tvg-logo="https://pics.filmaffinity.com/fast_x-556821969-large.jpg" group-title="Películas" tvg-name="Fast & Furious X",Fast & Furious X
acestream://5b6544f7e08744d5f5afcf666c01401fa28ac939
#EXTINF:-1 tvg-id="León por un Día" tvg-logo="https://pics.filmaffinity.com/one_day_as_a_lion-462508084-large.jpg" group-title="Películas" tvg-name="León por un Día",León por un Día
acestream://57c96618438d0b53a42ec257701875882f7ff7ba
#EXTINF:-1 tvg-id="Nadie te Salvará" tvg-logo="https://pics.filmaffinity.com/no_one_will_save_you-154423888-large.jpg" group-title="Películas" tvg-name="Nadie te Salvará",Nadie te Salvará
acestream://35c7f39fa7c8b68984f543ea54d656be62a8700e
#EXTINF:-1 tvg-id="The Equalizer 3" tvg-logo="https://pics.filmaffinity.com/the_equalizer_3-455060562-large.jpg" group-title="Películas" tvg-name="The Equalizer 3",The Equalizer 3
acestream://96e6f8a44e582fcdc74b6f6febfab3ceb50a83ec
#EXTINF:-1 tvg-id="Operación Kandahar" tvg-logo="https://pics.filmaffinity.com/kandahar-468918717-large.jpg" group-title="Películas" tvg-name="Operación Kandahar",Operación Kandahar
acestream://bb85e6a00741df944e4e4ad5cea69d8d7106e215
#EXTINF:-1 tvg-id="Operación Kandahar #2" tvg-logo="https://pics.filmaffinity.com/kandahar-468918717-large.jpg" group-title="Películas" tvg-name="Operación Kandahar #2",Operación Kandahar #2
acestream://5d5137d78b90c52ed245356e1f0c68e47cb33fce
#EXTINF:-1 tvg-id="Mi Crimen" tvg-logo="https://pics.filmaffinity.com/mon_crime-764108608-large.jpg" group-title="Películas" tvg-name="Mi Crimen",Mi Crimen
acestream://372abb4323a78318aea8ff841d36cff2c1ae6d27
#EXTINF:-1 tvg-id="Reality" tvg-logo="https://pics.filmaffinity.com/reality-296073317-large.jpg" group-title="Películas" tvg-name="Reality",Reality
acestream://b2684ac47cafda0c043e9b66939cea12342b7a4a
#EXTINF:-1 tvg-id="La Espía" tvg-logo="https://pics.filmaffinity.com/seule-400792324-large.jpg" group-title="Películas" tvg-name="La Espía",La Espía
acestream://aec5fa71fd30538bc82061b247b929e41f2395e5
#EXTINF:-1 tvg-id="Classica" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/e/e3/Stingray_Classica_RGB-02.svg/revision/latest/scale-to-width-down/250?cb=20191120223259" group-title="Vevo TV" tvg-name="Classica",Classica
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f779951372da90007fd45e8/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="VH1 Classics" tvg-logo="https://images.pluto.tv/channels/6076cd1df8576d0007c82193/colorLogoPNG.png" group-title="Vevo TV" tvg-name="VH1 Classics",VH1 Classics
https://i.mjh.nz/PlutoTV/6076cd1df8576d0007c82193-alt.m3u8
#EXTINF:-1 tvg-id="Vevo 2K" tvg-logo="https://images.pluto.tv/channels/5fd7bca3e0a4ee0007a38e8c/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo 2K",Vevo 2K
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5fd7bca3e0a4ee0007a38e8c/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="Vevo 70's" tvg-logo="https://images.pluto.tv/channels/5f32f26bcd8aea00071240e5/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo 70's",Vevo 70's
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f32f26bcd8aea00071240e5/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="Vevo 80's" tvg-logo="https://images.pluto.tv/channels/5fd7b8bf927e090007685853/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo 80's",Vevo 80's
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5fd7b8bf927e090007685853/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="Vevo 90's" tvg-logo="https://images.pluto.tv/channels/5fd7bb1f86d94a000796e2c2/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo 90's",Vevo 90's
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5fd7bb1f86d94a000796e2c2/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="Vevo Country" tvg-logo="https://images.pluto.tv/channels/5da0d75e84830900098a1ea0/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo Country",Vevo Country
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5da0d75e84830900098a1ea0/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="Vevo Pop" tvg-logo="https://images.pluto.tv/channels/5d93b635b43dd1a399b39eee/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo Pop",Vevo Pop
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5d93b635b43dd1a399b39eee/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="Vevo R&B" tvg-logo="https://images.pluto.tv/channels/5da0d83f66c9700009b96d0e/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo R&B",Vevo R&B
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5da0d83f66c9700009b96d0e/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="Vevo Reggeaton & Trap" tvg-logo="https://images.pluto.tv/channels/5f32f397795b750007706448/featuredImage.jpg?w=175&fm=jpg&q=75&fit=fill&fill=blur" group-title="Vevo TV" tvg-name="Vevo Reggeaton & Trap",Vevo Reggeaton & Trap
https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f32f397795b750007706448/master.m3u8?deviceId=channel&deviceModel=web&deviceVersion=1.0&appVersion=1.0&deviceType=rokuChannel&deviceMake=rokuChannel&deviceDNT=1&advertisingId=channel&embedPartner=rokuChannel&appName=rokuchannel&is_lat=1&bmodel=bm1&content=channel&platform=web&tags=ROKU_CONTENT_TAGS&coppa=false&content_type=livefeed&rdid=channel&genre=ROKU_ADS_CONTENT_GENRE&content_rating=ROKU_ADS_CONTENT_RATING&studio_id=viacom&channel_id=channel
#EXTINF:-1 tvg-id="eu music" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/5/54/EUMusiclogoz2013.jpg/revision/latest/scale-to-width-down/200?cb=20190724202920" group-title="Vevo TV" tvg-name="eu music",eu music
http://45.130.3.213:80/EU_Music/mpegts
#EXTINF:-1 tvg-id="Programacion Deportes Online" tvg-logo="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZqDl-ohUlUYxkPBswfosmQR3HpwrFaKc6KGFh1RkiWCLB9DKI-Mjv_yNp4XRJF2zzpUQ&usqp=CAU" group-title="Agenda Deportiva" tvg-name="Programacion Deportes Online",Programacion Deportes Online
https://www.futbolenlatv.es/deporte
#EXTINF:-1 tvg-id="Parrilla Movistar" tvg-logo="https://static.wikia.nocookie.net/logopedia/images/b/be/Movistar_.svg/revision/latest/scale-to-width-down/125?cb=20201030223306&path-prefix=es" group-title="Agenda Deportiva" tvg-name="Parrilla Movistar",Parrilla Movistar
https://www.movistarplus.es/programacion-tv
#EXTINF:-1 tvg-id="Fórmula Tv" tvg-logo="https://www.formulatv.com/favicon.ico" group-title="Agenda Deportiva" tvg-name="Fórmula Tv",Fórmula Tv
http://www.formulatv.com/programacion/movistarplus/
